### PR TITLE
Added UpdatePolicy to Column annotation. Which offers more flexibility around how columns are updated 

### PR DESCRIPTION
**Pull request by brandonkearby**
Hello DataStax java-driver team,

We had a use case where we wanted to append to a column that's a Collection type without first reading from cassandra. This pull request has our solution to that use case. We added a UpdatePolicy attribute to the Column annotation that lets you decide how it's handled (APPEND, PREPEND, OVERWRITE). The default of course is the current behavior of overwrite. This would be awesome if you could include this in the main line.

Thanks,

-Brandon

### CODE REVIEW

**Comment by olim7t** [comment]
Hi,
Sorry for leaving this unanswered for so long. We haven't focused enough on the mapper in the last 2.1 releases, but I plan to spend time on it for 2.1.6 (coming after 2.0.10).
You raise an interesting use case, although I must say I'm not a huge fan of having a `Mapper` instance do appends or prepends by default.

**Comment by brandonkearby** [comment]
Hi @olim7t , 
Thanks for getting back to me. I'm not a huge fan of having the Mapper do appends/prepends by default as well, and that's why I left the default behavior as overwrite. However, supporting append/prepend solves two problems. First, you don't have to read before write and secondly, you don't have to worry about race conditions.

I hope you consider this, so we don't have to keep this branch around.

Thanks,

-Brandon

**Comment by tolbertam** [comment]
Can one of the admins verify this patch?

**Comment by adutra** [comment]
Sorry again for being so unresponsive. We're making an effort to cleanup old PRs and see if they are still valid.

Unfortunately this patch won't apply cleanly on recent branches (post JAVA-541). @brandonkearby would you mind rebasing this on top of 3.x branch?

Your proposal is interesting, but I think you could achieve what you want using accessors, have you tried that?

**Comment by newkek** [comment]
fwiw I think that since this is an option on per-operation and not the mapping, I think it could qualify as well as an additional [Mapper.Option](http://docs.datastax.com/en/developer/java-driver/3.1/manual/object_mapper/using/#mapper-options), wdyt?

**Comment by adutra** [comment]
Closing as we are not going to add any new features to the mapper in the driver 3.x series. A new mapper API will be published after the 4.0 release.

@brandonkearby sorry for closing so abruptly but you didn't include any tests so it's hard to evaluate how stable this PR is, and I still think that we could achieve the same effect using accessors. Thanks anyway for your time and effort.

**Pull request closed without merging**
