### PR TITLE
JAVA-929 Fix equals method for index_interval columns.

### PR DESCRIPTION
**Pull request by tolbertam**
Fix for [JAVA-929](https://datastax-oss.atlassian.net/browse/JAVA-929).

### CODE REVIEW

**Comment by tolbertam** [comment]
Previously failing test `SchemaChangesTest#should_notify_of_table_update` on C\* 2.0.   Would consider table as changed when it didn't since index_interval was never considered as equal.   TableMetadataTest could use some better tests (some good tests on upstream branches), will work that on another ticket.

**Comment by tolbertam** [comment]
travis failing on should_stop_if_cancelled_between_attempts(com.datastax.driver.core.AbstractReconnectionHandlerTest) which is fixed on #443

**Comment by olim7t** [comment]
Merged. I amended your commit to also update hashCode.

**Comment by tolbertam** [comment]
Ah, great catch!  Didn't even think about the hashcode, glad you caught that :)

**Pull request merged**
