### PR TITLE
JAVA-733: Handle function calls and raw strings as non-idempotent in QueryBuilder.

### PR DESCRIPTION
**Pull request by adutra**

### CODE REVIEW

**Comment by olim7t** [comment]
Some of the more complex cases are not covered yet, but I'm not sure how far we want to go. The problem with function calls is that they can be nested arbitrarily deep. For example, this is not idempotent:

``` java
BuiltStatement bs = insertInto("foo").values(
    new String[]{ "k", "l" },
    new Object[]{ 1, ImmutableList.of(now()) });
```

**Comment by adutra** [comment]
Thanks for pointing that out, I added a check to `Insert.values()`. But like you said, the hunt for non idempotent ops is probably endless.

**Comment by olim7t** [comment]
Could you update the changelog?

**Comment by tolbertam** [comment]
Looks good to me! :+1:

**Comment by olim7t** [comment]
In hindsight I think we should be more conservative: currently the code uses a function blacklist, and a statement is idempotent unless proven otherwise. This is a bit fragile, especially with raw strings where we grep function calls (missing things like "`now ()`").

Even a whitelist won't work well, we need to consider Cassandra 2.2 where you can easily define a custom function that has the same name and same number of parameters as a standard one:

```
CREATE FUNCTION textasblob(x int) CALLED ON NULL INPUT RETURNS bigint LANGUAGE java
AS 'return System.currentTimeMillis();';
```

This means the whitelist should take parameter types into account, which is impractical.

So I'm tempted to make all function calls and raw strings non-idempotent by default. This is only a best guess, and the client can override it on the statement. Thoughts?

**Comment by olim7t** [comment]
Pushed minor changes.
@adutra if you agree with my commits, you can squash everything together and merge to 2.0.

**Comment by tolbertam** [comment]
looks good to me :+1:

**Pull request merged**
