### PR TITLE
Improve MAVEN build Performance

### PR DESCRIPTION
**Pull request by ChenZhangg**
[Parallel builds in Maven 3](https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3) Maven 3.x has the capability to perform parallel builds.

According to [Maven parallel test](https://www.baeldung.com/maven-junit-parallel-tests), we can run tests in parallel.

=====================
If there are any inappropriate modifications in this PR, please give me a reply and I will change them.

### CODE REVIEW

**Comment by adutra** [comment]
Hi @ChenZhangg thank you for your contribution.

First of all, your XML files are not well formatted and that is making the build fail:

```
Failed to execute goal au.com.acegi:xml-format-maven-plugin:3.1.1:xml-check (default) on project java-driver-parent: [xml-check] At least one XML file needs formatting, see the error logs above
```

But even if I format the files, the parallel execution of some unit tests are failing:

```
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR] com.datastax.oss.driver.internal.core.channel.ChannelFactoryAvailableIdsTest.should_report_available_ids(com.datastax.oss.driver.internal.core.channel.ChannelFactoryAvailableIdsTest)
[ERROR]   Run 1: ChannelFactoryAvailableIdsTest.should_report_available_ids » Channel address a...
[ERROR]   Run 2: ChannelFactoryAvailableIdsTest>ChannelFactoryTestBase.tearDown:286 » NullPointer
[INFO]
[ERROR] com.datastax.oss.driver.internal.core.channel.ChannelFactoryProtocolNegotiationTest.should_fail_if_version_specified_and_considered_beta_by_server(com.datastax.oss.driver.internal.core.channel.ChannelFactoryProtocolNegotiationTest)
[ERROR]   Run 1: ChannelFactoryProtocolNegotiationTest.should_fail_if_version_specified_and_considered_beta_by_server » Channel
[ERROR]   Run 2: ChannelFactoryProtocolNegotiationTest>ChannelFactoryTestBase.tearDown:286 » NullPointer
[INFO]
[ERROR] com.datastax.oss.driver.internal.core.channel.ChannelFactoryProtocolNegotiationTest.should_fail_if_version_specified_and_not_supported_by_server[0: 10](com.datastax.oss.driver.internal.core.channel.ChannelFactoryProtocolNegotiationTest)
[ERROR]   Run 1: ChannelFactoryProtocolNegotiationTest.should_fail_if_version_specified_and_not_supported_by_server[0: 10] » Channel
[ERROR]   Run 2: ChannelFactoryProtocolNegotiationTest>ChannelFactoryTestBase.tearDown:286 » NullPointer
[INFO]
[ERROR] com.datastax.oss.driver.internal.core.channel.ChannelFactoryProtocolNegotiationTest.should_fail_if_version_specified_and_not_supported_by_server[1: 0](com.datastax.oss.driver.internal.core.channel.ChannelFactoryProtocolNegotiationTest)
[ERROR]   Run 1: ChannelFactoryProtocolNegotiationTest.should_fail_if_version_specified_and_not_supported_by_server[1: 0] » Channel
[ERROR]   Run 2: ChannelFactoryProtocolNegotiationTest>ChannelFactoryTestBase.tearDown:286 » NullPointer
[INFO]
[ERROR] com.datastax.oss.driver.internal.core.channel.ChannelFactoryProtocolNegotiationTest.should_succeed_if_version_not_specified_and_server_supports_latest_supported(com.datastax.oss.driver.internal.core.channel.ChannelFactoryProtocolNegotiationTest)
[ERROR]   Run 1: ChannelFactoryProtocolNegotiationTest.should_succeed_if_version_not_specified_and_server_supports_latest_supported » Channel
[ERROR]   Run 2: ChannelFactoryProtocolNegotiationTest>ChannelFactoryTestBase.tearDown:286 » NullPointer
[INFO]
[ERROR] com.datastax.oss.driver.internal.core.channel.ChannelFactorySupportedOptionsTest.should_query_supported_options_on_first_channel(com.datastax.oss.driver.internal.core.channel.ChannelFactorySupportedOptionsTest)
[ERROR]   Run 1: ChannelFactorySupportedOptionsTest.should_query_supported_options_on_first_channel » Channel
[ERROR]   Run 2: ChannelFactorySupportedOptionsTest>ChannelFactoryTestBase.tearDown:286 » NullPointer
[INFO]
[INFO]
[ERROR] Tests run: 3205, Failures: 0, Errors: 6, Skipped: 0
```

The driver unit tests were not designed to be run in parallel, you would need to fix all the errors above.

Also, the unit tests execute relatively fast, so you wouldn't gain much time. The integration tests, however, are very long; but they are already parallelized. 

All in all, I don't think we're going to be able to accept this PR, sorry.

**Comment by ChenZhangg** [comment]
Let me try just using parallel builds....

**Comment by cstamas** [comment]
For better _developer experience_ instead of Maven Parallel builds I'd recommend using mvnd https://github.com/apache/maven-mvnd instead.

**Comment by absurdfarce** [comment]
Closing due to lack of activity over the past year.  You're free to update the pull request to the current master branch and re-submit if you'd like for us to take another look at this change.

**Pull request closed without merging**
