### PR TITLE
JAVA-923: Position idempotent flag on object mapper queries.

### PR DESCRIPTION
**Pull request by adutra**

### CODE REVIEW

**Comment by olim7t** [comment]
Maybe we could also position the `idempotent` flag on the queries generated for `Mapper`. I think they are all idempotent.

**Comment by adutra** [comment]
> Maybe we could also position the idempotent flag on the queries generated for Mapper. I think they are all idempotent.

I like the idea, but can we guarantee idempotence if the entity contains a computed field, e.g.

``` java
@Computed(value = "now()")
UUID lastUpdated;
```

This kind of thing might not make sense, but since people could write it, the SAVE query for such an entity would not be strictly idempotent.

**Comment by tolbertam** [comment]
Looks good to me!  :+1: Added a couple more tests and some test doc.

**Comment by olim7t** [comment]
> I like the idea, but can we guarantee idempotence if the entity contains a computed field

Computed fields are not included in save queries.

**Comment by adutra** [comment]
> Computed fields are not included in save queries.

Alright, went ahead and flagged all mapper-generated queries as idempotent.

**Pull request merged**
