### PR TITLE
Copyright to ASF 

### PR DESCRIPTION
**Pull request by michaelsembwever**
see https://incubator.apache.org/ip-clearance/cassandra-java-driver.html

### CODE REVIEW

**Comment by michaelsembwever** [comment]
Example checks
- `rg -i "Copyright DataStax"`  (manual replacement of license header)
- `rg -il "DataStax Java driver" | xargs sed -i '' 's/DataStax Java driver/Java Driver/gI'`

Patches for other branches:
 - https://github.com/datastax/java-driver/compare/4.12.x...thelastpickle:java-driver:mck/asf-donation/4.12.x
 - https://github.com/datastax/java-driver/compare/4.11.x...thelastpickle:java-driver:mck/asf-donation/4.11.x
 - https://github.com/datastax/java-driver/compare/4.8.0_fixes...thelastpickle:java-driver:mck/asf-donation/4.8.0_fixes
 - https://github.com/datastax/java-driver/compare/4.7.x...thelastpickle:java-driver:mck/asf-donation/4.7.x
 - https://github.com/datastax/java-driver/compare/4.6.x...thelastpickle:java-driver:mck/asf-donation/4.6.x
 - https://github.com/datastax/java-driver/compare/4.6.1_fixes...thelastpickle:java-driver:mck/asf-donation/4.6.1_fixes
 - https://github.com/datastax/java-driver/compare/4.5.x...thelastpickle:java-driver:mck/asf-donation/4.5.x
 - https://github.com/datastax/java-driver/compare/4.5.0_fixes...thelastpickle:java-driver:mck/asf-donation/4.5.0_fixes
 - https://github.com/datastax/java-driver/compare/4.4.0_fixes...thelastpickle:java-driver:mck/asf-donation/4.4.0_fixes
 - https://github.com/datastax/java-driver/compare/4.3.x...thelastpickle:java-driver:mck/asf-donation/4.3.x
 - https://github.com/datastax/java-driver/compare/4.3.0_fixes...thelastpickle:java-driver:mck/asf-donation/4.3.0_fixes
 - https://github.com/datastax/java-driver/compare/4.2.x...thelastpickle:java-driver:mck/asf-donation/4.2.x
 - https://github.com/datastax/java-driver/compare/4.1.0_fixes...thelastpickle:java-driver:mck/asf-donation/4.1.0_fixes
 - https://github.com/datastax/java-driver/compare/3.x...thelastpickle:java-driver:mck/asf-donation/3.x
 - https://github.com/datastax/java-driver/compare/3.10.x...thelastpickle:java-driver:mck/asf-donation/3.10.x
 - https://github.com/datastax/java-driver/compare/3.10.2_fixes...thelastpickle:java-driver:mck/asf-donation/3.10.2_fixes
 - https://github.com/datastax/java-driver/compare/3.5.x...thelastpickle:java-driver:mck/asf-donation/3.5.x
 - https://github.com/datastax/java-driver/compare/3.4.x...thelastpickle:java-driver:mck/asf-donation/3.4.x
 - https://github.com/datastax/java-driver/compare/3.3.x...thelastpickle:java-driver:mck/asf-donation/3.3.x
 - https://github.com/datastax/java-driver/compare/3.2.x...thelastpickle:java-driver:mck/asf-donation/3.2.x
 - https://github.com/datastax/java-driver/compare/3.1.x...thelastpickle:java-driver:mck/asf-donation/3.1.x
 - https://github.com/datastax/java-driver/compare/3.0.x...thelastpickle:java-driver:mck/asf-donation/3.0.x
 - https://github.com/datastax/java-driver/compare/2.2...thelastpickle:java-driver:mck/asf-donation/2.2
 - https://github.com/datastax/java-driver/compare/2.1...thelastpickle:java-driver:mck/asf-donation/2.1
 - https://github.com/datastax/java-driver/compare/2.0...thelastpickle:java-driver:mck/asf-donation/2.0
 - https://github.com/datastax/java-driver/compare/2.0.10_fixes...thelastpickle:java-driver:mck/asf-donation/2.0.10_fixes
 - https://github.com/datastax/java-driver/compare/2.0.9_fixes...thelastpickle:java-driver:mck/asf-donation/2.0.9_fixes
 - https://github.com/datastax/java-driver/compare/1.0...thelastpickle:java-driver:mck/asf-donation/1.0
 - https://github.com/datastax/java-driver/compare/docs_yaml...thelastpickle:java-driver:mck/asf-donation/docs_yaml

**Comment by hhughes** [comment]
```
git show -- ':!*.java'
```
If you want to look at any changes which aren't to .java files

**Comment by hhughes** [comment]
I notice in the new license we're using `Apache Cassandra` - no retail mark or anything else.

There are a few places where we use various different symbles after the name if we should be tidying those up at the same time:

```
% grep -h -r -o -E "Apache Cassandra[^ $]+" . | sort | uniq -c
   2 Apache Cassandra&copy;
  10 Apache Cassandra&reg;
   1 Apache Cassandra&trade;.
  27 Apache Cassandra(R)
   4 Apache Cassandra(R)'s
   1 Apache Cassandra(R).
   1 Apache Cassandra(R).</description>
   3 Apache Cassandra,
   7 Apache Cassandra®
   1 Apache Cassandra®.
   1 Apache Cassandra®:
   1 Apache Cassandra®]
   1 Apache Cassandra®]:
  13 Apache CassandraⓇ
```

**Comment by hhughes** [comment]
Github review UI is unusable for me with this patch :) I'm going to add feeback as main comments
```
diff --git a/manual/core/non_blocking/README.md b/manual/core/non_blocking/README.md
index a40779f8e..123d9ef1a 100644
--- a/manual/core/non_blocking/README.md
+++ b/manual/core/non_blocking/README.md
@@ -11,7 +11,7 @@ such as [Vert.x] or [Reactor], along with tools for automatic detection of block
 [Reactor]: https://projectreactor.io
 [BlockHound]: https://github.com/reactor/BlockHound
 
-**In summary, when used properly, the DataStax Java driver offers non-blocking guarantees for most 
+**In summary, when used properly, the Java driver offers non-blocking guarantees for most 
 of its operations, and during most of the session lifecycle.**
 
 These guarantees and their exceptions are detailed below. A final chapter explains how to use the 
```
~Nit 1: you've added a trailing space to the end of this changed line.~ sorry this is normal, not sure why git highlighted it such an angry red for me
Nit 2: Do we want to take this opportunity settle on casing of `Java Driver` vs `Java driver`? (most of those lines have been modified in this change)

**Comment by hhughes** [comment]
There are still a few matches for otherly cased `DataStax Java Driver`:
```
% grep -rl "DataStax Java Driver" --exclude-dir=.git 
./docs.yaml
./core/src/main/java/com/datastax/dse/driver/api/core/cql/continuous/ContinuousSession.java
./README.md
./manual/cloud/README.md
./examples/pom.xml
./examples/README.md
./osgi-tests/README.md
```

**Comment by michaelsembwever** [comment]
> Apache Cassandra

should be Apache Cassandra® on the first usage on any page.  but this is not critical.  (can be addressed later on.)

> There are still a few matches for otherly cased DataStax Java Driver

on it… 
Will standardise to "Java Driver" too.

**Comment by michaelsembwever** [comment]
All branches done.

**Comment by hhughes** [comment]
```
diff --git a/core/src/main/java/com/datastax/oss/driver/internal/core/metadata/token/ReplicationFactor.java b/core/src/main/java/com/datastax/oss/driver/internal/core/metadata/token/ReplicationFactor.java
index f20a472d9..966372da6 100644
--- a/core/src/main/java/com/datastax/oss/driver/internal/core/metadata/token/ReplicationFactor.java
+++ b/core/src/main/java/com/datastax/oss/driver/internal/core/metadata/token/ReplicationFactor.java
@@ -1,12 +1,14 @@
 package com.datastax.oss.driver.internal.core.metadata.token;
 /*
- * Copyright DataStax, Inc.
+ * Licensed to the Apache Software Foundation (ASF) under one
+ * or more contributor license agreements.  See the NOTICE file
...
```
Nit: the license in `core/src/main/java/com/datastax/oss/driver/internal/core/metadata/token/ReplicationFactor.java` comes after the package declaration (this is how it was before your refactoring) - any concern?

**Comment by michaelsembwever** [comment]
> Nit: the license in core/src/main/java/com/datastax/oss/driver/internal/core/metadata/token/ReplicationFactor.java comes after the package declaration (this is how it was before your refactoring) - any concern?

no concern

**Comment by hhughes** [comment]
```
% grep -rin "DataStax driver" --exclude-dir=.git 
./mapper-processor/src/main/java/com/datastax/oss/driver/internal/mapper/processor/SingleFileCodeGenerator.java:28:      "Generated by the DataStax driver mapper, do not edit directly.\n";
```

Nit: one mention of `DataStax driver` in mapper code generator - does this need to be changed?

**Comment by hhughes** [comment]
Python-script for filtering out common license change hunks from the diff: [license_change_diff_filter.py](https://gist.github.com/hhughes/00eb3219e9e90abdb83e5c6d6d1dd944#file-license_change_diff_filter-py)

**Review by hhughes — APPROVED** [review]
One remaining question about DataStax branding in `SingleFileCodeGenerator.java`, otherwise LGTM

**Review by hhughes — APPROVED** [review]
Re-approving this one

**Comment by michaelsembwever** [comment]
All merged.

**Pull request closed without merging**
