### PR TITLE
JAVA-961: Raise an exception when an older version of guava (< 16.0.1) is found.

### PR DESCRIPTION
**Pull request by tolbertam**
For [JAVA-961](https://datastax-oss.atlassian.net/browse/JAVA-961).

Introduces a check on reference of `CodecRegistry` where is creating a `TypeToken<Map<String,String>>` improperly sets the type information for the value type (`Object`/`V` instead of `String`) a warning is logged.

I'm unsure if this is the best way of determining this, but it seems pretty reliable.

When running with Guava 15.0 to 16.01, the following will happen when attempting to resolve a codec with more than one parameterized type argument:

```
WARN  [2015-10-22 18:57:20,308] [main] - Detected Guava Issue #1635 which indicates that a version of Guava less than 16.01 is in use.  This may introduce codec resolution issues in the driver, please upgrade to Guava 16.01 or later.
INFO  [2015-10-22 18:57:20,406] [main] - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
INFO  [2015-10-22 18:57:20,912] [main] - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
INFO  [2015-10-22 18:57:20,912] [main] - New Cassandra host /127.0.0.1:9042 added
INFO  [2015-10-22 18:57:20,913] [main] - New Cassandra host /127.0.0.2:9042 added
INFO  [2015-10-22 18:57:20,913] [main] - New Cassandra host /127.0.0.3:9042 added
Exception in thread "main" com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [varchar <-> V]
    at com.datastax.driver.core.CodecRegistry.notFound(CodecRegistry.java:711)
    at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:558)
    at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:539)
    at com.datastax.driver.core.CodecRegistry.maybeCreateCodec(CodecRegistry.java:613)
    at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:556)
    at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:539)
    at com.datastax.driver.core.CodecRegistry.access$200(CodecRegistry.java:153)
    at com.datastax.driver.core.CodecRegistry$TypeCodecCacheLoader.load(CodecRegistry.java:246)
    at com.datastax.driver.core.CodecRegistry$TypeCodecCacheLoader.load(CodecRegistry.java:243)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806)
    at com.datastax.driver.core.CodecRegistry.lookupCodec(CodecRegistry.java:516)
    at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:485)
    at com.datastax.driver.core.AbstractGettableByIndexData.codecFor(AbstractGettableByIndexData.java:81)
    at com.datastax.driver.core.AbstractGettableByIndexData.getMap(AbstractGettableByIndexData.java:346)
    at com.datastax.driver.core.AbstractGettableData.getMap(AbstractGettableData.java:26)
    at com.datastax.driver.core.AbstractGettableByIndexData.getMap(AbstractGettableByIndexData.java:335)
    at com.datastax.driver.core.AbstractGettableData.getMap(AbstractGettableData.java:26)
    at com.datastax.driver.core.AbstractGettableData.getMap(AbstractGettableData.java:233)
```

In this case the pre-emptive warning should give the user enough information to know that they need to upgrade guava.

In the case of using older versions of guava (<= 14.01) a `NoSuchMethodError` is raised while registering default codecs because `TypeToken.isPrimitive` is missing:

```
WARN  [2015-10-22 19:02:54,807] [main] - Detected Guava Issue #1635 which indicates that a version of Guava less than 16.01 is in use.  This may introduce codec resolution issues in the driver, please upgrade to Guava 16.01 or later.
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.reflect.TypeToken.isPrimitive()Z
    at com.datastax.driver.core.TypeCodec.<init>(TypeCodec.java:406)
    at com.datastax.driver.core.TypeCodec.<init>(TypeCodec.java:400)
    at com.datastax.driver.core.TypeCodec$BlobCodec.<init>(TypeCodec.java:947)
    at com.datastax.driver.core.TypeCodec$BlobCodec.<clinit>(TypeCodec.java:944)
    at com.datastax.driver.core.TypeCodec.blob(TypeCodec.java:248)
    at com.datastax.driver.core.CodecRegistry.<clinit>(CodecRegistry.java:180)
    at com.datastax.driver.core.Configuration$Builder.build(Configuration.java:267)
    at com.datastax.driver.core.Cluster$Builder.getConfiguration(Cluster.java:1228)
    at com.datastax.driver.core.Cluster.<init>(Cluster.java:113)
    at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:182)
    at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:1249)
```

In this case I consider the warning adequate information to know that the user needs to upgrade as well.

Thoughts on this strategy/idea?   Is the error descriptive enough? I can add tests (can add an integration test to osgi-examples) if this sounds ok.

### CODE REVIEW

**Comment by adutra** [comment]
lgtm in overall. 2 remarks:
- I wonder if `WARN` is enough; there is little chance that the driver could work properly with a bad Guava version.
- Not sure that `CodecRegistry` is the right place for this check. What about a separate `SanityChecks` class whose static initialization could be triggered from the static initialization of some central class e.g. `Cluster`?

**Comment by tolbertam** [comment]
I agree with both of your comments :+1: 

> I wonder if WARN is enough; there is little chance that the driver could work properly with a bad Guava version.

Good point, I think it is possible things could work with an older version of C\* that doesn't use map types in schema tables and if the user doesn't use them, but it definitely isn't something we should support so I agree that this should be raised to `ERROR`, will do!

> Not sure that CodecRegistry is the right place for this check. What about a separate SanityChecks class whose static initialization could be triggered from the static initialization of some central class e.g. Cluster?

I think that is probably the right thing to do.  Are there any other sanity checks that you think would be worth adding?  I think this is also a good idea as we'd use a separate logger which would allow the user to configure visibility separate from the `CodecRegistry` logger.

**Comment by adutra** [comment]
> Are there any other sanity checks that you think would be worth adding?

Maybe we can add there a check for the presence of native epoll transport. I think it's currently done when NettyOptions is instantiated.

It might also be a good place to print useful information about the driver (its version mostly). This is a feature that has been requested already in the mailing list, although I can't find a Jira ticket for it.

EDIT:

There is an ugly static initializer block in NettyUtil that does the epoll check.

**Comment by tolbertam** [comment]
Updated based on suggestions.   I added a static block in `Cluster` that calls `SanityChecks.check()` so the check is done at most once and as soon as `Cluster` is referenced.  The new error message looks like such:

< 15.0:

```
ERROR [2015-10-23 10:45:36,885] [main] - Detected Guava issue #1635 which indicates that a version of Guava less than 16.01 is in use.  This may introduce codec resolution issues or other problems in the driver, please upgrade to Guava 16.01 or later.
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.reflect.TypeToken.isPrimitive()Z
    at com.datastax.driver.core.TypeCodec.<init>(TypeCodec.java:406)
    at com.datastax.driver.core.TypeCodec.<init>(TypeCodec.java:400)
    at com.datastax.driver.core.TypeCodec$BlobCodec.<init>(TypeCodec.java:947)
    at com.datastax.driver.core.TypeCodec$BlobCodec.<clinit>(TypeCodec.java:944)
    at com.datastax.driver.core.TypeCodec.blob(TypeCodec.java:248)
    at com.datastax.driver.core.CodecRegistry.<clinit>(CodecRegistry.java:158)
    at com.datastax.driver.core.Configuration$Builder.build(Configuration.java:267)
    at com.datastax.driver.core.Cluster$Builder.getConfiguration(Cluster.java:1233)
    at com.datastax.driver.core.Cluster.<init>(Cluster.java:118)
    at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:187)
    at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:1254)
```

15.0-16.0:

```
ERROR [2015-10-23 10:47:15,851] [main] - Detected Guava issue #1635 which indicates that a version of Guava less than 16.01 is in use.  This may introduce codec resolution issues or other problems in the driver, please upgrade to Guava 16.01 or later.
INFO  [2015-10-23 10:47:16,002] [main] - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
WARN  [2015-10-23 10:47:16,422] [main] - Error while computing token map for datacenter DC1: could not achieve replication factor 1 (found 0 replicas only), check your keyspace replication settings.
INFO  [2015-10-23 10:47:16,422] [main] - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
INFO  [2015-10-23 10:47:16,423] [main] - New Cassandra host /127.0.0.1:9042 added
INFO  [2015-10-23 10:47:16,423] [main] - New Cassandra host /127.0.0.2:9042 added
INFO  [2015-10-23 10:47:16,423] [main] - New Cassandra host /127.0.0.3:9042 added
Exception in thread "main" com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [varchar <-> V]
    at com.datastax.driver.core.CodecRegistry.notFound(CodecRegistry.java:689)
    at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:536)
    at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:517)
    at com.datastax.driver.core.CodecRegistry.maybeCreateCodec(CodecRegistry.java:591)
    at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:534)
    at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:517)
    at com.datastax.driver.core.CodecRegistry.access$200(CodecRegistry.java:153)
    at com.datastax.driver.core.CodecRegistry$TypeCodecCacheLoader.load(CodecRegistry.java:224)
    at com.datastax.driver.core.CodecRegistry$TypeCodecCacheLoader.load(CodecRegistry.java:221)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
    at com.datastax.driver.core.CodecRegistry.lookupCodec(CodecRegistry.java:494)
    at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:463)
    at com.datastax.driver.core.AbstractGettableByIndexData.codecFor(AbstractGettableByIndexData.java:81)
    at com.datastax.driver.core.AbstractGettableByIndexData.getMap(AbstractGettableByIndexData.java:346)
    at com.datastax.driver.core.AbstractGettableData.getMap(AbstractGettableData.java:26)
    at com.datastax.driver.core.AbstractGettableByIndexData.getMap(AbstractGettableByIndexData.java:335)
    at com.datastax.driver.core.AbstractGettableData.getMap(AbstractGettableData.java:26)
    at com.datastax.driver.core.AbstractGettableData.getMap(AbstractGettableData.java:233)
```

**Comment by tolbertam** [comment]
> Maybe we can add there a check for the presence of native epoll transport. I think it's currently done when NettyOptions is instantiated.

I think it is ok to leave that as is because I don't think in the general use case that using epoll is going to help for the most part unless you have a lot of socket connections (over a thousand).

> It might also be a good place to print useful information about the driver (its version mostly). This is a feature that has been requested already in the mailing list, although I can't find a Jira ticket for it.

Big :+1: on exposing the driver version somehow.  If guava had something like that checking the version would be much easier than what is being done here.   I think it would be good to expose that as a static value on Cluster or somewhere else and then to also log it at some level as you suggest.  I'll open up another ticket if there isn't one already.

**Comment by adutra** [comment]
lgtm :+1:

**Comment by al3xandru** [comment]
re: exposing driver version: I was thinking we could expose something like the JVM properties and thus include more information (driver version, protocol version, jdk required, etc.). Part of these should also be logged when initializing.

**Comment by tolbertam** [comment]
Opened up [JAVA-969](https://datastax-oss.atlassian.net/browse/JAVA-969) for exposing driver version and other interesting properties in code.

Marking this PR as work in progress as would like to add tests for it after #494 is merged.

**Comment by adutra** [comment]
@tolbertam #494 is now merged.

**Comment by tolbertam** [comment]
@adutra Thanks! Will update this shortly.

**Comment by tolbertam** [comment]
Rebased and added tests to the osgi-examples project.  This should be good to go, let me know if there are any issues.  If merging feel free to squash before merge.

**Comment by olim7t** [comment]
Sorry to be late to the party, but is it enough to log an error? Since we're sure the driver won't work with that version, it would make sense to throw an unchecked exception like `IllegalStateException`.

**Comment by tolbertam** [comment]
Hmm, I think I agree with you.  There is a small chance of things working on an older version of C\* and not using Maps with guava 15, but I think it might be wrong to give the user the illusion that things would work just fine, even with logging that error as future minor releases may break a user if we utilize features in guava 16.01 that aren't in older versions.  I'll change this to throw an ISE unless anyone strongly disagrees.

**Comment by tolbertam** [comment]
Updated.  An `IllegalStateException` is now thrown.  I also updated the message to use stronger language.  Because `SanityChecks.check()` is done at static initialization of `Cluster` an `ExceptionInIniitializer` exception is thrown with `IllegalStateException` as the cause.

**Comment by adutra** [comment]
lgtm, are you ok for merging?

**Comment by tolbertam** [comment]
I didn't have any pending changes so it's good with me if @olim7t is ok with it.

**Comment by olim7t** [comment]
Yeah, I'm ok with it too.

**Comment by tolbertam** [comment]
Cool, I'll rebase and merge it, thanks!

**Pull request merged**
