### PR TITLE
JAVA-67: Utils.appendValueString creates a large amount of garbage patterns and strings

### PR DESCRIPTION
**Pull request by mschrag**

### CODE REVIEW

**Comment by mschrag** [comment]
@see JAVA-67 for discussion

**Comment by mschrag** [comment]
pulled Apache commons-lang's method in

**Comment by pcmanus** [comment]
I apologize, I know it's childish of me but I wanted to play at "beating" the commons method by using the fact we replace a single character. And I ended up committing that modified version (slightly faster and allocate a tiny bit less, even though that probably don't matter much in practice).

**Comment by mschrag** [comment]
haha .. i'm all for it. thanks.

**Pull request closed without merging**
