### PR TITLE
Fix eclipse compiler warnings

### PR DESCRIPTION
**Pull request by blair**

### CODE REVIEW

**Comment by pcmanus** [comment]
I'm good with most of this, but f4cb2ac doesn't compile, at least not with javac 6 (haven't try with java 7 tbh).

**Comment by blair** [comment]
Yes, I've switched to jdk 7.  I don't think its worth fighting the generics, how about merging everything but f4cb2ac?

**Comment by pcmanus** [comment]
> how about merging everything but f4cb2ac?

Sure. Just wanted to justify why I wont merge that last patch :)

**Comment by blair** [comment]
Yes, no problem ;)  I was thinking you were asking for a jdk 6 compatible fix.  I have JDK 6 on my box so was able to confirm the problem.

**Comment by pcmanus** [comment]
Alright, I'll pull the other commits "manually" so closing this one. I definitively agree it's not worth fighting the generics.

**Pull request closed without merging**
