### PR TITLE
Automatically register the codecs for CqlVectorType in CachingCodecRegistry

### PR DESCRIPTION
**Pull request by eolivelli**

### CODE REVIEW

**Review by lhotari — APPROVED** [review]

**Review by msmygit — APPROVED** [review]

**Comment by absurdfarce** [comment]
This is probably a useful idea for a future Java driver release but it is not required to add support for the vector type to dsbulk.  See [this PR](https://github.com/datastax/dsbulk/pull/475) for an example of how we can support the vector type in dsbulk using only a stock Java driver.

**Comment by eolivelli** [comment]
@absurdfarce I need this patch for the Cassandra Sink and not DSBulk.
The changes in DSBulk are not related

**Comment by eolivelli** [comment]
for reference:
https://github.com/datastax/pulsar-sink/pull/59

**Comment by absurdfarce** [comment]
This issue has been addressed by changes in #1666.  If there's something else we need to consider please re-open and add a comment!

**Pull request closed without merging**
