### PR TITLE
JAVA-1196: Include hash of result set metadata in prepared statement id.

### PR DESCRIPTION
**Pull request by adutra**
Opening this to allow reviews to start, but the original code dates back to June 2016 and the tests are failing after rebase.

### CODE REVIEW

**Comment by adutra** [comment]
C* test branch:
https://github.com/ifesdjeen/cassandra/tree/10786-trunk

**Comment by adutra** [comment]
@ifesdjeen I'm getting the following error when testing against your branch:

```
ERROR [SharedPool-Worker-1] 2017-01-18 11:02:34,053 ErrorMessage.java:338 - Unexpected exception during request
java.lang.NullPointerException: null
        at com.googlecode.concurrentlinkedhashmap.ConcurrentHashMapV8.get(ConcurrentHashMapV8.java:934) ~[concurrentlinkedhashmap-lru-1.4.jar:na]
        at com.googlecode.concurrentlinkedhashmap.ConcurrentLinkedHashMap.get(ConcurrentLinkedHashMap.java:672) ~[concurrentlinkedhashmap-lru-1.4.jar:na]
        at org.apache.cassandra.cql3.QueryProcessor.getStoredPreparedStatement(QueryProcessor.java:442) ~[main/:na]
        at org.apache.cassandra.cql3.QueryProcessor.prepare(QueryProcessor.java:390) ~[main/:na]
        at org.apache.cassandra.cql3.QueryProcessor.prepare(QueryProcessor.java:385) ~[main/:na]
        at org.apache.cassandra.cql3.QueryProcessor.prepare(QueryProcessor.java:379) ~[main/:na]
        at org.apache.cassandra.transport.messages.PrepareMessage.execute(PrepareMessage.java:78) ~[main/:na]
```

**Comment by ifesdjeen** [comment]
I'll have to take a look, it's been quite some time since the last time it worked, might be a  bug or just that the codebases diverged a lot. I'll take a look soon.

**Comment by tolbertam** [comment]
After looking at this a little bit I realized that this code is probably out of date.  I took a look at @ifesdjeen's java-driver fork and found [ifesdjeen/java-driver#10786-release](https://github.com/ifesdjeen/java-driver/tree/10786-release) as the most recent branch with these changes.

I rebased that branch against 3.x and ran it against [ifesdjeen/cassandra#10786-trunk](https://github.com/ifesdjeen/cassandra/tree/10786-trunk) and it worked with one small change (change QueryOptions Flag to be parsed as int instead of byte as that was a recent V5 proto change) that was needed since that branch is out of sync with trunk.

@ifesdjeen can you confirm that [ifesdjeen/java-driver#10786-release](https://github.com/ifesdjeen/java-driver/tree/10786-release) is the correct version we should be working with?  I'm pretty confident that it is but just wanted to double check.   If that is the case I'll create a new PR and will also push up a C* branch on my fork that has the QueryOptions flag change.

**Comment by tolbertam** [comment]
created [java1196-new](https://github.com/datastax/java-driver/tree/java1196-new) from [ifesdjeen/java-driver#10786-release](https://github.com/ifesdjeen/java-driver/tree/10786-release) rebased on 3.x.    Used [tolbertam/10786-queryflags](https://github.com/tolbertam/cassandra/tree/10786-queryflags) to test it.

**Comment by adutra** [comment]
> created java1196-new from ifesdjeen/java-driver#10786-release rebased on 3.x. Used tolbertam/10786-queryflags to test it.

@tolbertam should we close this one and open another one based on java1196-new?

**Comment by tolbertam** [comment]
> @tolbertam should we close this one and open another one based on java1196-new?

sgtm, I'll open that PR up (edit: #794), thanks!

**Comment by adutra** [comment]
Closing in favor of #794.

**Pull request closed without merging**
