### PR TITLE
Cleanup maven dependencies and some configurations. 

### PR DESCRIPTION
**Pull request by splatch**
Extract version placeholders.
Introduced dependency management.
Improved OSGi packaging (via maven placeholders).
Removed dependency to netty from OSGi bundle.
Cleaned up license/developers section as it was duplicated.

### CODE REVIEW

**Comment by tolbertam** [comment]
Hi @splatch, it looks like we have some compatible goals!  Quite recently I created #297 that was merged in yesterday to extract versions into properties defined in the parent module so they may be overridden.  Per [project guidelines](https://github.com/datastax/java-driver/blob/2.1/CONTRIBUTING.rst#working-on-an-issue) would you mind rebasing against 2.0 and reopening the PR request against the 2.0 branch?

**Comment by olim7t** [comment]
Regarding your changes to the OSGI configuration, we want to keep `shadedArtifactAttached=true`: upcoming features like [JAVA-640](https://datastax-oss.atlassian.net/browse/JAVA-640) will leak Netty to the public API, so they will require a non-shaded JAR; we still want to provide the shaded JAR for users not interested in them.

**Comment by splatch** [comment]
I wasn't aware of JAVA-640, I will update pull request to keep shaded JAR.

Also will rebase to 2.0 branch.

**Comment by splatch** [comment]
I updated commit for 2.1. For 2.0 branch is not yet done cause I started from never branch. Backporting is harder than merging.

**Pull request closed without merging**
