### PR TITLE
JAVA-335: throw meaningful error when trying to use a closed Cluster.

### PR DESCRIPTION
**Pull request by olim7t**
Previously this lead to a `RejectedExecutionException` by one of the closed executors, which made the cause of the error unclear.

I've left `Cluster.newSession` as is, to preserve its contract ("it cannot fail").

Reconnection at initialization time was also discussed in JAVA-335. I will create a separate issue for that.

### CODE REVIEW

**Comment by pcmanus** [comment]
Looks good, though I think I'd have rather throw an IllegalStateException. This is more of a programmer error than something you'd want to properly catch in your application so I'm not sure it's worth a new exception. Not a big deal though, I can live with a new exception if you have a strong preference.

**Comment by pcmanus** [comment]
Aside: fyi if you include something like 'JAVA-335 #fixes' somewhere in the commit message, it will automatically link the commit in JIRA once committed.

**Comment by olim7t** [comment]
Totally agree about using IllegalStateException. I will fix that and the commit message this afternoon.

**Comment by olim7t** [comment]
Updated.
I put the "Send to testing" JIRA transition, which I think is the most appropriate one.

**Comment by pcmanus** [comment]
> I put the "Send to testing" JIRA transition, which I think is the most appropriate one.

Sure. Though JIRA was ignoring the #fixes transition anyway, the only thing I personally care about is that the commit is linked from JIRA. Also, I'm good with getting fancy with JIRA transition but let's make sure we don't leave ticket open indefinitely in 'testing' because we don't have a proper testing process yet.

**Comment by olim7t** [comment]
OK. The issue name is enough to get the commits linked, so I'll probably dispense with the transitions from now on.

**Pull request merged**
