### PR TITLE
Java 465

### PR DESCRIPTION
**Pull request by bsideup**

### CODE REVIEW

**Comment by olim7t** [comment]
Merged, thanks.

FYI, I have squashed your two commits into fd4155d, the commit is still attributed to you.

**Comment by bsideup** [comment]
Thanks!

Btw, any ETA on 2.1.2?

**Comment by olim7t** [comment]
"Soon" :-)
No precise date yet, but most of v3 protocol is now supported, I'm working on the last bits right now. Including QA, I would say expect it in the coming weeks.

**Comment by bsideup** [comment]
cool, thanks:)

On Wed, Sep 24, 2014 at 11:47 AM, Olivier Michallat <
notifications@github.com> wrote:

> "Soon" :-)
> No precise date yet, but most of v3 protocol is now supported, I'm working
> on the last bits right now. Including QA, I would say expect it in the
> coming weeks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datastax/java-driver/pull/230#issuecomment-56641496.

## 

Best regards,
Sergei Egorov

**Pull request closed without merging**
