### PR TITLE
Add ResultSetFuture#getUninterruptibly(Iterable<ResultSetFuture>).

### PR DESCRIPTION
**Pull request by blair**
Since Java Driver supports asynchronous queries it is useful to fire
off multiple asynchronous queries and want to wait for all of them to
complete.  This static method provides that functionality.

### CODE REVIEW

**Comment by pcmanus** [comment]
In that case, I think I'd rather let people call Futures.allAsList themselves (I'll admit there is a bit of arbitrary in that choice, but let's say that there is a bunch of interesting things that guava's Futures provides, and that it feels better to me to leave it to Guava rather than re-encapsulating those features).

Now it's true that it can be convenient to have the exception extraction part, but I think I'd rather expose that feature and let people compose it with other Futures functions.

**Comment by blair** [comment]
I'd agree with you, but doing it correctly with extractCauseFromExecutionException() makes it 8 lines of code, not just an additional one or two, a non-trivial amount of code.

People using Java Driver and not looking at the source code won't know that they should check the ExecutionException for its cause, so its better for everybody for Java Driver to provide it.

I already have a copy of this function in my project since I'm doing writes to three tables, waiting, then three reads, waiting and then three writes.  Seems wasteful to have people duplicate it.

Regarding composition, there's really no other way that I can think of for the List version to behave.  It shouldn't behave differently than the single future version in regards to exceptions.  One wouldn't want the List version to behave differently.  If we make extractCauseFromExecutionException() public they can compose it, but Java Driver should provide a good default version for users.

**Comment by pcmanus** [comment]
Sorry, this has been closed automatically because we've removed the master branch (we've decided to stick to version branches to make things more stable in the future). That being said, I still have to think about that one. Could be easier to add a JIRA ticket to track this, though I'll make sure to look close at this issue soonish.

**Comment by blair** [comment]
I've opened https://datastax-oss.atlassian.net/browse/JAVA-176 to discuss this with an improved version.

**Comment by blair** [comment]
I've opened https://datastax-oss.atlassian.net/browse/JAVA-176 with an improved design.

**Pull request closed without merging**
