### PR TITLE
UUID parse opt' , javadoc fixes , other minor changes (IDEA inspections)

### PR DESCRIPTION
**Pull request by snazy**
- removed superfluous String.format() calls
- replaced single character strings with chars
- replaced one regex with precompiled pattern
- replaced tail recursion with loop

### CODE REVIEW

**Comment by pcmanus** [comment]
Thanks for the contribution. There was a need for some minor rebasing (and I usually don't like clicking on the 'merge pull request' button when there is more than one commit, being them trivial) so I cherry-picked but most of it is committed.

I did left out the UUID parsing commit for now because that's not just a code cleanup and deserve imo a separate attention. Typically, I'd rather create a JIRA (https://datastax-oss.atlassian.net/browse/JAVA) for the sake a giving it the proper attention (and out of curiosity, how much faster is that than the jdk parsing?).

**Comment by ghost** [comment]
The built-in UUID parser is slower than can be implemented in Java?? Wow. Is it because your cersion skips Unicode support? And is dropping Unicode support desireable? I vote no, it may create problems for users with non US keyboards.

**Comment by snazy** [comment]
Jacob, can you cite where RFC4122 (https://www.ietf.org/rfc/rfc4122.txt) defines Unicode support?

And yes, jdk's variant is too slow. Dig into the source.

**Comment by ghost** [comment]
Some keyboards don't insert normal numbers, but unicode numbers. Your patch would break the case where some people type in a UUID manually. Admittedly this is a border case, but its a real use case. 

I am not suggesting Cassandra or its drivers should _store_ UUID's in a non standard format, What I am saying is this:
- If you have been using the built in UUID parser, you could have databases with UUID's (stored in string format) that use unicode. So fetching data may break in some cases if you change this behaviour.
- If this change were made, it would inconvenience a subset of non US users.

My suggestion would be that internally Cassandra could use a non unicode supporting UUID parser, but at any point data might be being received from a user it should use the Java UUID parser.

In case other s are not aware of what we are talking about, see the following test case:

```
import java.util.UUID;

public class UuidTest {

        public static void main(String[] arg) {

                // Works
                System.out.println(UUID.fromString("6C07FA04-DD06-429E-8355-8F00A8CDB342"));

                // Wide numbers could include \uff10-ff19 This works!
                System.out.println(UUID.fromString("6C07FA0\uFF11-DD06-429E-8355-8F00A8CDB342"));

                // Dashes could include: \u2012-2015 - This fails
                //System.out.println(UUID.fromString("6C07FA04\u2015DD06-429E-8355-8F00A8CDB342"));
        }

}
```

**Pull request closed without merging**
