### PR TITLE
JAVA-716 - SSL hostname verification

### PR DESCRIPTION
**Pull request by spodkowinski**
See https://datastax-oss.atlassian.net/browse/JAVA-716

### CODE REVIEW

**Comment by olim7t** [comment]
Hi,
Unfortunately we're still backward compatible with Java 6 (which is why the Travis build failed), where `setEndpointIdentificationAlgorithm` does not exist.
`SSLOptions` allows providing your own `SSLContext` but I don't think it will be enough, I've not found any way to configure `SSLContext` for what you want to do.
So maybe we should allow `SSLOptions` to take an `SSLEngine` directly.

**Comment by spodkowinski** [comment]
The SSLEngine instance needs to be created for the specific remote host and port. You can't create it just once and pass it along with SSLOptions. Maybe a factory interface would work instead, which would have to be implemented by the user. However, I'd prefer an API that would make it as easy as possible to use secure SSL connections out of the box, instead of just offering extension points that would just leave it to the user to implement some very specialized, security relevant code.

**Comment by tolbertam** [comment]
Can one of the admins verify this patch?

**Comment by olim7t** [comment]
I've created [JAVA-841](https://datastax-oss.atlassian.net/browse/JAVA-841) to refactor the SSLOptions API.

In the meantime, there's a workaround: you can use [NettyOptions#afterChannelInitialized](http://docs.datastax.com/en/drivers/java/2.1/com/datastax/driver/core/NettyOptions.html#afterChannelInitialized%28io.netty.channel.socket.SocketChannel%29) to register the SSL handler yourself (see the Javadocs which explain how to do this). That's a bit less user-friendly, but it will give you control over the SSLEngine instance.

**Pull request closed without merging**
