### PR TITLE
JAVA-2164: Rename statement builder methods to setXxx

### PR DESCRIPTION
**Pull request by tomekl007**

### CODE REVIEW

**Comment by tomekl007** [comment]
Should we change `with*` to `set*` for `SessionBuilder` as well?

**Review by olim7t — CHANGES_REQUESTED** [review]
Looks good on the code side 👍 
Please add a changelog entry.
The manual also needs to be updated. I did a text search for the regex `with\w` in all `*.md` files and found relevant matches in the following directories:
* faq/
* manual/core/:
  * idempotence/
  * paging/
  * performance/
  * query_timestamps/
  * statements/prepared/
  * statements/simple/
  * tracing/

**Comment by olim7t** [comment]
I went ahead and did the manual, it was almost as fast as pointing out where the changes were.
The changelog is still to do.

**Comment by tomekl007** [comment]
> I went ahead and did the manual, it was almost as fast as pointing out where the changes were.
> The changelog is still to do.

Thx! :) I've added the changelog entry

**Review by olim7t — APPROVED** [review]

**Pull request merged**
