### PR TITLE
JAVA-347: support User Defined Types in mapper

### PR DESCRIPTION
**Pull request by olim7t**

### CODE REVIEW

**Comment by pcmanus** [comment]
Some remarks:
- The main problem we have is that the field in a UDTDefinition _must_ be in the same order than the order in which they have been defined in Cassandra since the serialization format depends on it. And Class.getDeclaredField clearly states that the returned field are in no particular order so we can't rely on it being the declaraion order. So I think we need to fetch the UDTDefinition from the Session object (based on the UDT name) rather than building the UDTDefinition from the class fields. This does create a dependency on the Session object but I think the alternatives are not worth it. Note that this is also why we shouldn't make the UDTDefinition ctor public: the order of field matters and we want that to be an implementation detail. As a side note, we also don't need to make UDTValue ctor public since there is a `UDTDefinition.newValue` method for that.
- I'm really not a fan of having anything reflection related in the core module, and in fact I'd rather not make neither the `DataType.of` methods nor the Reflection class public at all, since they are both kind of a mapping implementation detail.
- Not super fan of the "Nested" naming either. Can't we s/Nested/UDT/ since that's the name we use all over the place?
- I'd like us to expose UDTMapper the same way we expose Mapper. The only method we'll want to make public however is a `T map(UDTValue v)` (i.e. the method currently named `toNestedEntity` but let's rename it to `map`).
- I'd rather not reuse @Column for UDTs. For UDT we use "fields" in the Cassandra documentation/implementation so let's have a @Field annotation instead.
- It's a nit, but I'd also rename @UserDefinedType to @UDT. It's shorter and we use the abbreviation all over the place anyway.

Also, 2 minor code style points:
- I would really really appreciate it if you configured your text editor to remove end of line spaces.
- For imports, I've tried to stick to 1) java._, 2) all except com.datastax.driver._ and 3) com.datastax.driver.*. For consistency it would be nice to continue sticking to that (there is few cases where the patch reorder existing imports in a difference way in particular).

**Comment by olim7t** [comment]
Thanks for the review, I'll start working on that.

Sorry about the imports, I must have used Eclipse's "organize imports" a couple of times. I'll customize it to fit your style.

**Comment by olim7t** [comment]
Here are the changes.

Note that the `Field` and `Column` annotations being processed by the same code, it is currently not enforced that they are used in the right place, i.e. you could use a `Column` for a UDT and a `Field` for a table. There might be a way to prevent that, but I thought it wasn't worth it.

I've kept my commits separate, which will make it easier for me if you have comments about particular aspects. I'll squash everything in two commits (like the original ones) when we are done.

Also, I realize that I've been rebasing and force-pushing my pull-requests. Is it OK for you, or would you prefer that I append the changes?

**Comment by pcmanus** [comment]
I committed this thanks.

I did added a couple modifs on top of it. First I did a s/Nested/UDT (that's a detail but that was bugging me). More importantly, I removed the DataType.serialize/deserialize method variants with no protocol versions: I think defaulting to NEWEST_SUPPORTED_PROTOCOL is actually dangerous/error prone because that may not at all be the version in use. The proper default would be to use the version in use by the cluster, but we can't get that easily. So overall I think it's safer to just break the API, making it clear that there is something for people to do, rather than silently using a default that will be broken for a fair amount of people.

This last change leds to a bunch of other change where the protocol version needs to be passed around, but those changes are actually necessary to properly support bother version 2 and version 3 of the protocol at the same time so I went ahead.

**Comment by pcmanus** [comment]
> Note that the Field and Column annotations being processed by the same code, it is currently not enforced that they are used in the right place, i.e. you could use a Column for a UDT and a Field for a table. There might be a way to prevent that, but I thought it wasn't worth it.

Btw, that's not priority number one, but I do think we should fix that ultimately. Imo, we should validate annotation as strictly as possible as it can avoid confusion and mistakes.

**Pull request merged**
