### PR TITLE
JAVA-1346: Reset heartbeat only on client reads (not writes)

### PR DESCRIPTION
**Pull request by adutra**

### CODE REVIEW

**Comment by tolbertam** [comment]
looks good, have a test for this, will push up shortly.

**Comment by tolbertam** [comment]
Added a test, fails on 3.0.x but passes on this branch, feel free to squash :) 👍

**Review by tolbertam — APPROVED** [review]

**Review by olim7t — APPROVED** [review]
LGTM
Nit: could we update the title to describe the actual change, rather than the initial problem? Suggestion: "Reset heartbeat only on client reads (not writes)"

**Comment by adutra** [comment]
Squashed and rebased, should be ready to go.

**Pull request merged**
