### PR TITLE
Trivial fixes

### PR DESCRIPTION
**Pull request by joaquincasares**
- Nicer formatting for -Pdocs.
- Allow `coverage --samplecode` to run with -Pdocs
- One last pass over same error message from before
- Added `nodetool ring` option to CCMBridge, for debugging purposes.

### CODE REVIEW

**Comment by pcmanus** [comment]
Out of curiosity, what is the goal of those "doc" tests? A priori, tests whose whole goal is to print stuff feels a bit hackish to me. Is that generally useful?

**Comment by pcmanus** [comment]
So I have my personal doubts about this "doc" tests things but if you think that's useful, I can live with it, for now at least.

**Comment by joaquincasares** [comment]
\o/. I'll make a note of the future "doc" group tests on future pull requests.

So far it's provided our docs team with sample CQL statements when they had syntax questions. In the future, I'm hoping to break up our QueryBuilder tests for simpler digestion and thus an easy guide for our docs team to parse and integrate on their end.

In the far future: full blown examples of connecting, importing, reading, and writing are planned.

**Comment by pcmanus** [comment]
Just for the record, don't consider that as my blessing for using tests for other things than tests, I will have a problem if we add more of those.

**Comment by joaquincasares** [comment]
Oh no, just for clarification, I wasn't planning on having many more, if any, tests that only print out code.

I was planning on applying the "doc" label, along with the primary "unit" or "integration" groups, for java-code that will help docs.

Maven case: running -Pdoc will print the above print statements, then ensure the subsection of "integration" tests that docs use will get tested. Reality: our docs team can search for these "doc" tests and can copy-paste this code into docs.

Either way, this will be a "hidden" feature and only used by our docs team (and possibly useful for developing test cases for our other drivers, but we'll see if this is even the case).

**Pull request merged**
