### PR TITLE
Count uninitialized connections in conviction policy (JAVA-966).

### PR DESCRIPTION
**Pull request by olim7t**

### CODE REVIEW

**Comment by olim7t** [comment]
Force-pushed to rebase on current 2.0.

**Comment by tolbertam** [comment]
Observed an AssertionError while running a test in ConvictionPolicy while forceClosing a pool as result of a connection failing

```
16:12:55 Starting com.datastax.driver.core.RecommissionedNodeTest.should_ignore_recommissioned_node_on_session_init [Test #85]...
16:13:02     818435 [main] INFO  com.datastax.driver.core.CCMBridge  - Stopping: 127.0.1.1
16:13:11     827208 [main] INFO  com.datastax.driver.core.policies.DCAwareRoundRobinPolicy  - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
16:13:11     827209 [main] INFO  com.datastax.driver.core.Cluster  - New Cassandra host /127.0.1.2:9042 added
16:13:11     827209 [main] INFO  com.datastax.driver.core.Cluster  - New Cassandra host /127.0.1.1:9042 added
16:13:11     827303 [cluster34-nio-worker-1] WARN  io.netty.channel.DefaultChannelPipeline  - An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
16:13:11 java.lang.AssertionError
16:13:11    at com.datastax.driver.core.ConvictionPolicy$DefaultConvictionPolicy.signalConnectionFailure(ConvictionPolicy.java:103)
16:13:11    at com.datastax.driver.core.Cluster$Manager.signalConnectionFailure(Cluster.java:2034)
16:13:11    at com.datastax.driver.core.Connection.defunct(Connection.java:410)
16:13:11    at com.datastax.driver.core.Connection$2.create(Connection.java:198)
16:13:11    at com.google.common.util.concurrent.Futures$FallbackFuture$1.onFailure(Futures.java:468)
16:13:11    at com.google.common.util.concurrent.Futures$4.run(Futures.java:1140)
16:13:11    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
16:13:11    at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150)
16:13:11    at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135)
16:13:11    at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203)
16:13:11    at com.google.common.util.concurrent.Futures$ChainingListenableFuture$1.run(Futures.java:882)
16:13:11    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
16:13:11    at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150)
16:13:11    at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135)
16:13:11    at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203)
16:13:11    at com.google.common.util.concurrent.Futures$ChainingListenableFuture$1.run(Futures.java:882)
16:13:11    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
16:13:11    at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150)
16:13:11    at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135)
16:13:11    at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203)
16:13:11    at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:855)
16:13:11    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
16:13:11    at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150)
16:13:11    at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135)
16:13:11    at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203)
16:13:11    at com.datastax.driver.core.DefaultResultSetFuture.onException(DefaultResultSetFuture.java:159)
16:13:11    at com.datastax.driver.core.Connection$Dispatcher.errorOutAllHandler(Connection.java:1048)
16:13:11    at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1122)
16:13:11    at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1107)
16:13:11    at com.datastax.driver.core.HostConnectionPool.forceClose(HostConnectionPool.java:184)
16:13:11    at com.datastax.driver.core.HostConnectionPool.access$300(HostConnectionPool.java:43)
16:13:11    at com.datastax.driver.core.HostConnectionPool$2.onFailure(HostConnectionPool.java:156)
16:13:11    at com.google.common.util.concurrent.Futures$4.run(Futures.java:1140)
16:13:11    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
16:13:11    at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150)
16:13:11    at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135)
16:13:11    at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203)
16:13:11    at com.google.common.util.concurrent.Futures$CombinedFuture.setOneValue(Futures.java:1551)
16:13:11    at com.google.common.util.concurrent.Futures$CombinedFuture.access$400(Futures.java:1441)
16:13:11    at com.google.common.util.concurrent.Futures$CombinedFuture$2.run(Futures.java:1514)
16:13:11    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
16:13:11    at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150)
16:13:11    at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135)
16:13:11    at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203)
16:13:11    at com.google.common.util.concurrent.Futures$FallbackFuture$1.onFailure(Futures.java:489)
16:13:11    at com.google.common.util.concurrent.Futures$4.run(Futures.java:1140)
16:13:11    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
16:13:11    at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150)
16:13:11    at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135)
16:13:11    at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203)
16:13:11    at com.google.common.util.concurrent.Futures$FallbackFuture$1$1.onFailure(Futures.java:484)
16:13:11    at com.google.common.util.concurrent.Futures$4.run(Futures.java:1140)
16:13:11    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
16:13:11    at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150)
16:13:11    at com.google.common.util.concurrent.ExecutionList.add(ExecutionList.java:106)
16:13:11    at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:170)
16:13:11    at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1152)
16:13:11    at com.google.common.util.concurrent.Futures$FallbackFuture$1.onFailure(Futures.java:473)
16:13:11    at com.google.common.util.concurrent.Futures$4.run(Futures.java:1140)
16:13:11    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
16:13:11    at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150)
16:13:11    at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135)
16:13:11    at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203)
16:13:11    at com.google.common.util.concurrent.Futures$ChainingListenableFuture$1.run(Futures.java:882)
16:13:11    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
16:13:11    at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150)
16:13:11    at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135)
16:13:11    at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203)
16:13:11    at com.google.common.util.concurrent.Futures$ChainingListenableFuture$1.run(Futures.java:882)
16:13:11    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
16:13:11    at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150)
16:13:11    at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135)
16:13:11    at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203)
16:13:11    at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:895)
16:13:11    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
16:13:11    at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150)
16:13:11    at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135)
16:13:11    at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
16:13:11    at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:131)
16:13:11    at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:154)
16:13:11    at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1002)
16:13:11    at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:935)
16:13:11    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
16:13:11    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
16:13:11    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
16:13:11    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254)
16:13:11    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
16:13:11    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
16:13:11    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
16:13:11    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
16:13:11    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
16:13:11    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242)
16:13:11    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
16:13:11    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
16:13:11    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847)
16:13:11    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
16:13:11    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
16:13:11    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
16:13:11    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
16:13:11    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
16:13:11    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
16:13:11    at java.lang.Thread.run(Thread.java:701)
```

``` java
        @Override
        boolean signalConnectionFailure(Connection connection) {
            if (host.state != Host.State.DOWN)
                updateReconnectionTime();

            int remaining = openConnections.decrementAndGet();
            assert remaining >= 0;  <--- here
            Host.statesLogger.debug("[{}] {} failed, remaining = {}", host, connection, remaining);
            return remaining == 0;
        }
```

**Comment by tolbertam** [comment]
That last change seems to have resolved the issue (no errors after 2+ hours) of a contact point failing to connect for control connection and not decrementing openConnections, nice!

**Comment by tolbertam** [comment]
Have not reproduced the AssertionError since last fix after 200 test runs (was happening to 1 out of 6 configurations in jenkins).  :+1:

**Pull request merged**
