### PR TITLE
JAVA-2918 Ignore invalid peers in schema agreement check

### PR DESCRIPTION
**Pull request by annamalai87**
fixes https://datastax-oss.atlassian.net/browse/JAVA-2918

### CODE REVIEW

**Comment by annamalai87** [comment]
@adutra PTAL when you have a chance.

**Comment by annamalai87** [comment]
@olim7t @adutra Please see if you have a chance to review. Jira ticket https://datastax-oss.atlassian.net/browse/JAVA-2918

**Comment by adutra** [comment]
@annamalai87 I plan to review this week, don't worry. And thanks for the PR :-)

**Review by adutra — APPROVED** [review]
Looking really good, thank you for you contribution. I pushed a commit with some cosmetic changes, and that messed up a bit with the commit history, but I will fix that myself.

**Comment by adutra** [comment]
@annamalai87  sorry to bother you but I need you to sign our CLA please:

https://cla.datastax.com/

Please ping me when you've signed it. Many thanks!

**Comment by annamalai87** [comment]
Signed.

Thanks,
Annamalai

**Pull request merged**
