### PR TITLE
Update metrics to the latest version

### PR DESCRIPTION
**Pull request by beckje01**
Latest version changed groupId to io.dropwizard.metrics from com.codahale.metrics

### CODE REVIEW

**Comment by beckje01** [comment]
Should I rebase this against 2.0 branch?

**Comment by tolbertam** [comment]
Can one of the admins verify this patch?

**Comment by adutra** [comment]
IMHO just to be on the safe side I would introduce this change in 2.2 only, unless there is something in the new Metrics version that we absolutely need?

**Comment by beckje01** [comment]
Nope happy to target any branch.

**Comment by tolbertam** [comment]
@olim7t / @adutra any thoughts about including this in the 3.0.0 beta?  Would be good time to upgrade to the newest metrics.

**Comment by adutra** [comment]
@tolbertam good suggestion! @beckje01 would you mind rebasing against 3.0?

**Comment by beckje01** [comment]
Closing and retargeting it at 3.0

**Pull request closed without merging**
