### PR TITLE
Take into account new "frozen" attribute

### PR DESCRIPTION
**Pull request by olim7t**
@pcmanus this is a work in progress, I wanted to make sure we agree on the `Frozen` annotation before I start implementing checks in the mapper.

There's a catch because we can't annotate type parameters on a collection (this will come in Java 8), so I've added a `targets` attribute:

``` java
@Frozen
private Address address;

@Frozen(targets = {Target.VALUE)}
private List<Address> addresses;

@Frozen(targets = {Target.KEY, Target.VALUE)}
private Map<CustomType1, CustomType2> someMap;
```

For tuples, this gets even more complicated because of nesting. But if the goal is schema generation, we'll have to provide the tuple type anyway because `TupleValue` does not provide enough information, so I suggest we include the whole tuple definition in an annotation:

``` java
@TupleDefinition("tuple<text, frozen<tuple<int, int>>>")
private TupleValue someTuple;
```

### CODE REVIEW

**Comment by mfiguiere** [comment]
Why do you need a `@Frozen` annotation? Is it because you consider it as something worth to double check just like primary keys? If it's mostly for DDL generation then I'd prefer to postpone the introduction of this annotation until we introduce a complete DDL generation feature, otherwise it would be confusing to have this annotation and not things like `@SecondaryIndex`.

**Comment by pcmanus** [comment]
> There's a catch because we can't annotate type parameters on a collection

As of 2.1.0, the only places where you can put an `frozen` (and there is no choice currently for those in fact) are tuples and UDT. So I'd suggest postponing the addition of this `target` for now, just for the sake of not risking introducing something that turns out to not be perfectly adapted to what ends up in Cassandra, and also because we can't really test it right now. Do keep the code around because it will likely be needed soonish though.
This holds for tuples to: there is currently no need to have frozen any other place than top-level. And we've slightly punt on it for 2.1.0, but we might end up deciding that tuple are kind of frozen "by default" and so we might end up not having to deal with nesting of frozen inside tuples (discussion around this should happens on [CASSANDRA-7859](https://issues.apache.org/jira/browse/CASSANDRA-7859).

> Why do you need a `@Frozen` annotation?

This is a fair question. The plan regarding Cassandra is roughtly this: currently we only support frozen UDT. This comes with some limitations, like the fact that you can't update subfields of a UDT without rewriting it all. Later (in C\* 3.0), we'll introduce non-frozen UDT, that won't have those limitations (though they will have some of their minor limitations like not being allowing in PK columns or map keys, so frozen UDT will stil have their use). So while UDT are, as of C\* 2.1, frozen by default, C\* still forces you to add the frozen keyword so as to not break the upgrade to 3.0.
A similar reasoning could be the motivation here. Currently, the mapper probably don't need the `@frozen` annotation to work. But not forcing it today means that if when there is non-frozen UDT it turns out that you do _need_ the `@frozen` annotation for some things, then er might have a small upgrade problem.

So my inclination would be to require the annotation and check it because 1) we'll want it to generate schema anyway and 2) it's a guarantee that you won't have to force people to add back `@frozen` on all their pre-existing use of UDT when C\* 3.0 comes out.

**Comment by olim7t** [comment]
> As of 2.1.0, the only places where you can put an frozen (and there is no choice currently for those in fact) are tuples and UDT.

Yes, but this also applies to collection elements:

```
create table foo(i int primary key, l list<frozen<bar>>);
```

In Java this would be mapped to a `List<Bar>`. Do you mean that the `Frozen` annotation, when applied to a collection, should implicitly refer to its element type(s)?

I can see that becoming a backwards-compatibility issue if map values are ever allowed to be unfrozen:

``` java
// without `targets`, this would map to "map<frozen<foo>, frozen<bar>>"
@Frozen
private Map<Foo, Bar> m;

// but if in the future we want to map "map<frozen<foo>, bar>":
@Frozen(targets = { Target.KEY }
private Map<Foo, Bar> m;
```

**Comment by pcmanus** [comment]
bq. Yes, but this also applies to collection elements

You're right, I was too quick in dismissing that. Well, I guess we do need to handle it somehow. My only small beef with `targets` is that it's unclear how it extends to further nesting, that is, if you have

``` java
private Map<String, Map<String, Foo>>
```

and want to apply the `@frozen` to `Foo`. Let me clarify that this is not supported by C\* currently, but it will most probably be support with C\* 3.0. So having a solution that extends naturally to it would be one less thing to worry about in the future. That said, I don't have a much better idea that the `targets` you propose. It's a shame we can't annotate type parameters.

**Comment by olim7t** [comment]
```
private Map<String, Map<String, Foo>>
```

You are right, I had overlooked that. We'll probably need [nested annotations](https://blogs.oracle.com/toddfast/entry/creating_nested_complex_java_annotations) then.

**Comment by olim7t** [comment]
This is getting painful: nested annotations don't allow recursion, so there is no way to represent a tree structure. We need to encode the coordinates of the types we want to freeze; one of the less ugly attempts I can come up with is:

``` java
@Frozen({
    @FrozenSubtype({ Target.VALUE, Target.VALUE })
})
private Map<String, Map<String, Foo>> m;
```

Meaning: to reach `Foo` from the root, go right, then right. Ouch.

Another option is to encode the type in a string, as I initially suggested for tuples:

``` java
@Frozen("map<text, map<text, frozen<foo>>>")
private Map<String, Map<String, Foo>> m;
```

**Comment by pcmanus** [comment]
Having the type in a string almost seem the lesser of two evils. But it's still evil.

**Comment by olim7t** [comment]
Agreed. It seems acceptable for deeply nested collections (which should not come up that often), and we can assume that the empty string means the type itself. But for simple collections it sucks.

**Comment by olim7t** [comment]
I've thought of a compromise: adding two shorthand annotations for simple collections.

That would give us:

``` java
// Top-level:
@Frozen
private Foo foo;

// Simple collections:
@FrozenValue
private List<Foo> foos;
@FrozenKey @FrozenValue
private Map<Foo, Bar> barsByFoo;

// Nested collections:
@Frozen("map<text, map<text, frozen<foo>>>")
private Map<String, Map<String, Foo>> m;
```

**Comment by pcmanus** [comment]
That could be reasonable. It's obviously still not ideal, but probably the most pragramtic solution so far.

**Comment by olim7t** [comment]
Just pushed final version, I will merge it tomorrow.

**Pull request merged**
