### PR TITLE
JAVA-200: EC2 specific load balancing policy

### PR DESCRIPTION
**Pull request by OskarKjellin**

### CODE REVIEW

**Comment by tolbertam** [comment]
Can one of the admins verify this patch?

**Comment by Jan-M** [comment]
:+1: Bumping this idea. But if I am not mistaken, one would need to connect this with a token awarenes and some kind of Cassandra Server support to prefer rack local nodes, otherwise your client may just speak to a same rack coordinator node but this one will ignore locality?

This is in our case mostly pressing not due to latency but due to billing / costs on AWS with AZ-AZ transfer in same region. We are reading a lot of metric data with consistency level set to one and due to ELB/client distribution we send too much data around imho.

**Comment by OskarKjellin** [comment]
As far as I know, there's no difference in cost within same AZ compared to different AZ in same region. Going cross region does have extra cost tho

https://aws.amazon.com/ec2/faqs/#Billing

**Comment by Jan-M** [comment]
Hmm.. when you go to Billing -> Data transfer there is:

Data Transfer IN to Amazon EC2 From:

image

Similar for OUT:
image

That is free vs. 0.01$ per GB.

**Comment by Jan-M** [comment]
Looks like I can indeed use the TokenAware policy wrapping your EC2 AZ Aware policy as you map same az and in same region to HostDistance.LOCAL and .REMOTE ignoring real remotes. Which is good enough for me.

**Comment by OskarKjellin** [comment]
Yeah apparently there was different cost for that, wasn't aware. 
I ran that policy for a while in production and it worked well for me there.

**Comment by adutra** [comment]
Closing as this hasn't received any recent comments and we are now deprecating any form of cross-DC failover in the driver, see [JAVA-2041](https://datastax-oss.atlassian.net/browse/JAVA-2041). Thanks @OskarKjellin for your time and effort!

**Pull request closed without merging**
