### PR TITLE
Customizable creation of netty timer (JAVA-853)

### PR DESCRIPTION
**Pull request by mironp**

### CODE REVIEW

**Comment by tolbertam** [comment]
Was just in a discussion with someone and we broached the topic of sharing `HashedWheelTimer` instances between `Cluster` instances.   Netty will log a nasty warning at 4 \* number of processors active `HashedWheelTimer` instances so if a user has that many clusters they'll see this warning:

> io.netty.util.ResourceLeakDetector: LEAK: You are creating too many HashedWheelTimer instances.  HashedWheelTimer is a shared resource that must be reused across the JVM,so that only a few instances are created.

Was instantly reminded of this pull request and thought maybe what should be done instead is add a `hashedWheelTimer(ThreadFactory threadFactory)` method to `NettyOptions`.  This way the user would have control over whether or not `HashedWheelTimer` was shared and also how it is constructed.  This would also cover the case of setting the ticks and interval since the user has complete control over how the `HashedWheelTimer` is created.   We would also need to update the docs on `onClusterClose` to state that this method should also address stopping `HashedWheelTimer` as well (if applicable).

@mironp @olim7t @adutra what do you think?

**Comment by adutra** [comment]
@tolbertam :+1: for adding a `hashedWheelTimer(ThreadFactory threadFactory)` method instead. `NettyOptions` is already particular in that it does not return settings that allow the driver to create objects, it manipulates such objects directly (EventLoopGroup mainly), thus allowing resource sharing. We should IMHO keep that in mind for HashedWheelTimer as well.

**Comment by olim7t** [comment]
+1 for injecting the timer instead of its constructor parameters.

Users of the shaded version of the driver will still be able to create an instance, only they will have to use the shaded Netty packages.

@mironp could you update your pull request? Also, could you mention the ticket in `changelog/README.md` under 2.0.11?

**Comment by olim7t** [comment]
LGTM :+1:

**Comment by adutra** [comment]
lgtm :+1:

**Comment by tolbertam** [comment]
lgtm as well :+1:

**Comment by olim7t** [comment]
Merged to 2.0, will be part of 2.0.11.
Thanks @mironp !

**Pull request merged**
