### PR TITLE
Added changes to support columns list for GET queries.

### PR DESCRIPTION
**Pull request by vagifzeynalov**
Example:

```
public T get(K1 pk1, K2 pk2, Set<String> columns) {
    return mapper().get(pk1, pk2, columns);
}

final Entity entiry = dao.get(key1, key2, ImmutableSet.of("col1", "col2"));
```

### CODE REVIEW

**Comment by olim7t** [comment]
Changed base branch since we plan to rename 3.0 to 3.x.

**Comment by adutra** [comment]
This can be easily achieved already with one of the following methods:

1. Using an accessor:

```
@Accessor
public interface EntityAccessor {

    @Query("SELECT col1, col2 FROM entity WHERE key1 = ? AND key1 = ?")
    Entity findEntity(int key1, int key2);

}
```

2. Using a custom resultset:

```
ResultSet rs = session.execute("SELECT col1, col2 FROM entity WHERE key1 = ? AND key2 = ?", key1, key2);
Entity entity = dao.map(rs).one();
```

Globally I'm not sure the use case is general enough to fit inside the mapper.

**Comment by vagifzeynalov** [comment]
@adutra it is general enough, since the mapper itself uses it inside of it at line 107
`PreparedStatement getPreparedQuery(QueryType type, Set<ColumnMapper<?>> columns, EnumMap<Option.Type, Option> options) {
`
It was there before my change.

Why not to provide the ability for the top level classes to pass the columns list?

**Comment by adutra** [comment]
Closing as we are not going to add any new features to the mapper in the driver 3.x series. A new mapper API will be published after the 4.0 release.

@vagifzeynalov sorry for closing so abruptly but you didn't include any tests so it's hard to evaluate how stable this PR is, and I still think that we could achieve the same effect using accessors. Thanks anyway for your time and effort.

**Pull request closed without merging**
