### PR TITLE
Improve IdentifierIndex firstIndexOf performance

### PR DESCRIPTION
**Pull request by chibenwa**
Avoids doing two hasmap lookups and instead does a single one, thus improving performances (CPU) of rougthly 33%.

In applications reading lots of rows and not managing manually indexes (which is tricky, boiler plate and error prone),
IdentifierIndex::firstIndexOf is typically a CPU hotspots. In reactive applications it might even run on the driver event loop. As such, performances gains here are welcome.

## Before

```
Benchmark                             Mode  Cnt  Score   Error  Units
IdentifierIndexBench.complexGetFirst  avgt    5  0.046 ± 0.005  us/op
IdentifierIndexBench.simpleGetFirst   avgt    5  0.046 ± 0.002  us/op
```

## After

```
Benchmark                             Mode  Cnt  Score   Error  Units
IdentifierIndexBench.complexGetFirst    avgt    5  0.028 ± 0.002  us/op
IdentifierIndexBench.simpleGetFirst     avgt    5  0.030 ± 0.002  us/op
```

[Use ImmutableListMultimap within IdentifierIndex](https://github.com/datastax/java-driver/pull/1615/commits/1631b6d8c3e8a9cc46d5388382f40f527bb6a558)
[1631b6d](https://github.com/datastax/java-driver/pull/1615/commits/1631b6d8c3e8a9cc46d5388382f40f527bb6a558)

This unlocks massive performance gains upon reads, for a minor slow
down at instanciation time, which won't be felt by applications relying
on prepared statements.

## Before

```
Benchmark                               Mode  Cnt  Score   Error  Units
IdentifierIndexBench.complexAllIndices  avgt    5  0.007 ± 0.001  us/op
IdentifierIndexBench.complexGetFirst    avgt    5  0.026 ± 0.002  us/op
IdentifierIndexBench.createComplex      avgt    5  0.759 ± 0.059  us/op
IdentifierIndexBench.createSimple       avgt    5  0.427 ± 0.048  us/op
IdentifierIndexBench.simpleAllIndices   avgt    5  0.007 ± 0.001  us/op
IdentifierIndexBench.simpleGetFirst     avgt    5  0.027 ± 0.002  us/op
```

## After

```
Benchmark                               Mode  Cnt  Score    Error  Units
IdentifierIndexBench.complexAllIndices  avgt    5  0.004 ±  0.001  us/op
IdentifierIndexBench.complexGetFirst    avgt    5  0.005 ±  0.001  us/op
IdentifierIndexBench.createComplex      avgt    5  0.680 ±  0.020  us/op
IdentifierIndexBench.createSimple       avgt    5  0.538 ±  0.096  us/op
IdentifierIndexBench.simpleAllIndices   avgt    5  0.004 ±  0.001  us/op
IdentifierIndexBench.simpleGetFirst     avgt    5  0.005 ±  0.001  us/op
```

### CODE REVIEW

**Comment by chibenwa** [comment]
JMH code used here:

```
package com.datastax.oss.driver.internal.core.data;

import java.util.concurrent.TimeUnit;

import org.junit.Test;
import org.openjdk.jmh.annotations.Benchmark;
import org.openjdk.jmh.annotations.Mode;
import org.openjdk.jmh.infra.Blackhole;
import org.openjdk.jmh.runner.Runner;
import org.openjdk.jmh.runner.options.Options;
import org.openjdk.jmh.runner.options.OptionsBuilder;
import org.openjdk.jmh.runner.options.TimeValue;

import com.datastax.oss.driver.api.core.CqlIdentifier;
import com.datastax.oss.driver.shaded.guava.common.collect.ImmutableList;

public class IdentifierIndexBench {
    private static final CqlIdentifier ID_1 = CqlIdentifier.fromCql("id1");
    private static final CqlIdentifier ID_2 = CqlIdentifier.fromCql("id2");
    private static final CqlIdentifier ID_3 = CqlIdentifier.fromCql("id3");
    private static final IdentifierIndex SIMPLE_INDEX = new IdentifierIndex(ImmutableList.of(ID_1, ID_2, ID_3));
    private static final IdentifierIndex COMPEX_INDEX = new IdentifierIndex(ImmutableList.of(ID_1, ID_2, ID_3, ID_1, ID_2, ID_3));

    @Test
    public void launchBenchmark() throws Exception {
        Options opt = new OptionsBuilder()
            .include(this.getClass().getName() + ".*GetFirst")
            .mode (Mode.AverageTime)
            .timeUnit(TimeUnit.MICROSECONDS)
            .warmupTime(TimeValue.seconds(5))
            .warmupIterations(3)
            .measurementTime(TimeValue.seconds(2))
            .measurementIterations(5)
            .threads(1)
            .forks(1)
            .shouldFailOnError(true)
            .shouldDoGC(true)
            .build();

        new Runner(opt).run();
    }

    @Benchmark
    public void simpleGetFirst(Blackhole bh) {
        bh.consume(SIMPLE_INDEX.firstIndexOf(ID_1));
    }

    @Benchmark
    public void complexGetFirst(Blackhole bh) {
        bh.consume(COMPEX_INDEX.firstIndexOf(ID_1));
    }

    @Benchmark
    public void simpleAllIndices(Blackhole bh) {
        bh.consume(SIMPLE_INDEX.allIndicesOf(ID_1));
    }

    @Benchmark
    public void complexAllIndices(Blackhole bh) {
        bh.consume(COMPEX_INDEX.allIndicesOf(ID_1));
    }

    @Benchmark
    public void createSimple(Blackhole bh) {
        bh.consume(new IdentifierIndex((ImmutableList.of(ID_1, ID_2, ID_3))));
    }

    @Benchmark
    public void createComplex(Blackhole bh) {
        bh.consume(new IdentifierIndex((ImmutableList.of(ID_1, ID_2, ID_3, ID_1, ID_2, ID_3))));
    }
}
```

**Comment by chibenwa** [comment]
As expressed in https://github.com/datastax/java-driver/pull/1614#issuecomment-1305005793 this work is where big easy gains are. 

@absurdfarce any feedback on this work?

**Comment by absurdfarce** [comment]
@chibenwa I want to spend a little more time with this one but my strong inclination is to agree that there's a solid, easy win here.  I'll try to have this wrapped up in the next few days.

**Comment by adutra** [comment]
@chibenwa this is awesome.

Would it be worth exploring the idea of going one step further and precomputing the first indices?

Something like:

```java
public class IdentifierIndex {

  private final ListMultimap<CqlIdentifier, Integer> byId;
  private final ListMultimap<String, Integer> byCaseSensitiveName;
  private final ListMultimap<String, Integer> byCaseInsensitiveName;
  private final ImmutableMap<CqlIdentifier, Integer> firstById;
  private final ImmutableMap<String, Integer> firstByCaseSensitiveName;
  private final ImmutableMap<String, Integer> firstByCaseInsensitiveName;

  public IdentifierIndex(List<CqlIdentifier> ids) {
    ImmutableListMultimap.Builder<CqlIdentifier, Integer> byId = ImmutableListMultimap.builder();
    ImmutableListMultimap.Builder<String, Integer> byCaseSensitiveName = ImmutableListMultimap.builder();
    ImmutableListMultimap.Builder<String, Integer> byCaseInsensitiveName = ImmutableListMultimap.builder();

    int i = 0;
    for (CqlIdentifier id : ids) {
      byId.put(id, i);
      byCaseSensitiveName.put(id.asInternal(), i);
      byCaseInsensitiveName.put(id.asInternal().toLowerCase(Locale.ROOT), i);
      i += 1;
    }

    this.byId = byId.build();
    this.byCaseSensitiveName = byCaseSensitiveName.build();
    this.byCaseInsensitiveName = byCaseInsensitiveName.build();

    firstById = this.byId.entries()
        .stream()
        .collect(ImmutableMap.toImmutableMap(Entry::getKey, Entry::getValue, (i1, i2) -> i1));
    firstByCaseSensitiveName = this.byCaseSensitiveName.entries()
        .stream()
        .collect(ImmutableMap.toImmutableMap(Entry::getKey, Entry::getValue, (i1, i2) -> i1));
    firstByCaseInsensitiveName = this.byCaseInsensitiveName.entries()
        .stream()
        .collect(ImmutableMap.toImmutableMap(Entry::getKey, Entry::getValue, (i1, i2) -> i1));
  }

  /**
   * Returns all occurrences of a given name, given the matching rules described in {@link
   * AccessibleByName}.
   */
  public List<Integer> allIndicesOf(String name) {
    return Strings.isDoubleQuoted(name)
        ? byCaseSensitiveName.get(Strings.unDoubleQuote(name))
        : byCaseInsensitiveName.get(name.toLowerCase(Locale.ROOT));
  }

  /**
   * Returns the first occurrence of a given name, given the matching rules described in {@link
   * AccessibleByName}, or -1 if it's not in the list.
   */
  public int firstIndexOf(String name) {
    return Strings.isDoubleQuoted(name)
        ? firstByCaseSensitiveName.getOrDefault(Strings.unDoubleQuote(name), -1)
        : firstByCaseInsensitiveName.getOrDefault(name.toLowerCase(Locale.ROOT), -1);
  }

  /** Returns all occurrences of a given identifier. */
  public List<Integer> allIndicesOf(CqlIdentifier id) {
    return byId.get(id);
  }

  /** Returns the first occurrence of a given identifier, or -1 if it's not in the list. */
  public int firstIndexOf(CqlIdentifier id) {
    return firstById.getOrDefault(id, -1);
  }
}
```

**Comment by chibenwa** [comment]
Hello,

Thanks for the enthousiasm.

However I realized today that the massive gains are because ImmutableStuff from guava do a `==` call prior to hashing. The benchs written above leveraged that in the **massive** gains.

I wonder how this would thansfer to applications in the wild to be fairly honnest: if I use the same CqlIdentifier constant to build the statement AND when accessing the row would the driver preserve the `==` ? If so we have the gains, if not, that would be more limited. (I played quickly with a debugger and it looked like "no")

Given that new knowledge I did do a new run of the benchmarks. Still meaningful. I included your proposal @adutra but it do not bring enhancements so I think it would not be worth the pain...

```
// 4.x
Benchmark                             Mode  Cnt  Score   Error  Units
IdentifierIndexBench.complexGetFirst  avgt    5  0.115 ± 0.005  us/op
IdentifierIndexBench.simpleGetFirst   avgt    5  0.108 ± 0.006  us/op

// PR-1 c150185 
Benchmark                             Mode  Cnt  Score   Error  Units
IdentifierIndexBench.complexGetFirst  avgt    5  0.097 ± 0.003  us/op
IdentifierIndexBench.simpleGetFirst   avgt    5  0.091 ± 0.014  us/op

// PR 1631b6d8c3e8a9cc46d5388382f40f527bb6a558
Benchmark                             Mode  Cnt  Score   Error  Units
IdentifierIndexBench.complexGetFirst  avgt    5  0.060 ± 0.001  us/op
IdentifierIndexBench.simpleGetFirst   avgt    5  0.073 ± 0.014  us/op

// @adutrat proposal
Benchmark                             Mode  Cnt  Score   Error  Units
IdentifierIndexBench.complexGetFirst  avgt    5  0.073 ± 0.011  us/op
IdentifierIndexBench.simpleGetFirst   avgt    5  0.068 ± 0.004  us/op
```

Still a `1/3` gain though.

**Comment by absurdfarce** [comment]
@chibenwa I've been pulled into other things and haven't been able to give this as much attention as I'd hoped to but my inclination is to merge it in its current state.  I haven't been able to shape the sense that there's even more to gain here but I also haven't been able to put that sense into concrete code.  And either way your point above is very persuasive to me; even if there were some other enhancements the code above represents a clear improvement over 4.x and merging it doesn't prevent any future work on this point.

@adutra Any objection from you?

**Comment by adutra** [comment]
> @adutra Any objection from you?

No objections, and thank @chibenwa for the thorough benchmarks you did.

**Comment by absurdfarce** [comment]
Sounds like we have agreement all around.  I'm merging this as it stands and we can revisit for additional enhancements in the future.  Thanks again to @chibenwa for the work here and to @adutra for his input.

**Pull request merged**
