### PR TITLE
Suggestion to autodiscover seeds using dns a-records

### PR DESCRIPTION
**Pull request by olvesh**
This will make the cluster not only use the first available `InetAddress` but all that is returned from the host lookup.

I feel that this will greatly simplify setups as we can add a single cassandra_seeds dns record and have that statically added to our configuration.

Docs will follow.

### CODE REVIEW

**Comment by olim7t** [comment]
Hi,
This is a good idea. Two minor remarks:
- we feel that this should not be enabled by default, so could you make it a separate builder method (something like `addMultipleIpContactPoint`)?
- this should also be on the 2.0 branch, so could you do your PR against that branch instead of 2.1?

Thanks

**Comment by olvesh** [comment]
Sure - will do! Will you apply on both branches then after I add it to 2.0?

**Comment by olim7t** [comment]
Yes, it will be merged on 2.1 (most likely for 2.1.7).

**Comment by olvesh** [comment]
Although - if you have a host with many ip addresses on it - my suggestion would make it more transparent. I understand the thing about existing functionality though, but if some existing user has many ip-addresses on the host of a cassandra server address wouldn't this be wanted behaviour anyway?

The driver would handle any duplicates or ip's that are not answering anyway I guess?

**Comment by olim7t** [comment]
Ignore the reference above, that was a mistake.

**Pull request closed without merging**
