### PR TITLE
JAVA-1256: Log parameters of BuiltStatement

### PR DESCRIPTION
**Pull request by gfelisberto**
com.datastax.driver.core.querybuilder.BuiltStatment (INSERT/UPDATE and others) do not get Logged with parameters. This adds support.

### CODE REVIEW

**Comment by adutra** [comment]
Thank you @gfelisberto for your contribution, indeed it seems that we forgot `BuiltStatement` when implementing the `QueryLogger`.

**Comment by adutra** [comment]
Created [JAVA-1256](https://datastax-oss.atlassian.net/browse/JAVA-1256) to track this pull-request. 

Also would you mind adding a test to `QueryLoggerTest` to verify that your changes fix the issue? Thanks!

**Comment by gfelisberto** [comment]
Hope this small test helps. I tried mimicking the existing ones but there was one annotation (@CassandraVersion(major = 2.0)) that I do not know if it is correct.

**Comment by olim7t** [comment]
Change the base branch since we plan to rename 3.0 to 3.x. We should also consider targeting this earlier than 3.2.0, in a way it can be considered as a bugfix.

**Comment by adutra** [comment]
We have a more ambitious refactoring of `QueryLogger` going on in #755. We cannot merge both unfortunately.

**Comment by adutra** [comment]
Closing in favor of #1138.

**Pull request closed without merging**
