### PR TITLE
Cassandra Socks5 Proxy options

### PR DESCRIPTION
**Pull request by mashkoor-Ahmed**
I have a requirement to get a number of applications/services to route their Cassandra traffic through a Socks5 proxy layer. 

This has proven to be an easy task for many of these services as they make use of the com.datastax.driver.core.Cluster library - this library exposes methods such as Cluster.withNettyOptions() which makes routing Cassandra traffic through a proxy possible, following the example in this blog post: https://community.datastax.com/questions/851/connection-to-a-cluster-via-a-socks-proxy.html

However, my instance of Kafka-Connect-Cassandra uses the Datastax/Kafka-Sink library (which consumes this Java-Driver library under the hood) - which sadly does not expose any way to route Cassandra traffic through a Socks 5 proxy. This PR is an attempt to inner source and implement this feature.

The accompanying Kafka-Sink PR to this change is as follows: https://github.com/datastax/kafka-sink/pull/131

### CODE REVIEW

**Comment by mashkoor-Ahmed** [comment]
Hello folks @adutra @olim7t @tolbertam @emerkle826 @absurdfarce 
Any chance I could get some help in troubleshooting the Travis CI - Branch build? It seems to be stuck in a pending state unlike the Pull Request build.

Any code reviews and help to get this change approved/merged/released would also be much appreciated 🙂

**Comment by jdonenine** [comment]
Hi @mashkoor-Ahmed thanks for the heads up on the CI pipeline - we've see the issue but haven't yet had a chance to look into it.

We're hoping to review your PR soon to include in an upcoming release and I've created an issue for tracking purposes of that [here](https://datastax-oss.atlassian.net/browse/JAVA-2985).

In the mean time, before we can consider merging the changes we'll need you to sign our CLA agreement, you can find it at https://cla.datastax.com.

Thanks for the contribution!

**Comment by mashkoor-Ahmed** [comment]
Hello @jdonenine ,
Thanks for the reply - looking forward to the review!
I believe I've signed the CLA agreement already last week - do please let me know if there were any issues with it or my declaration isn't visible on your side.

**Comment by mashkoor-Ahmed** [comment]
Hi @jdonenine - just wanted to check in and see if there was any update on this PR? And also to see if there is a rough timeline for when I can expect this change to be included in an upcoming release. Thanks in advance

**Comment by absurdfarce** [comment]
Closing due to lack of activity over the past year.  You're free to update the pull request to the current master branch and re-submit if you'd like for us to take another look at this change.

**Pull request closed without merging**
