### PR TITLE
JAVA-3085: Initialize c.d.o.d.i.core.util.Dependency at Graal native image build-time

### PR DESCRIPTION
**Pull request by hhughes**

### CODE REVIEW

**Comment by absurdfarce** [comment]
I tried this change with a couple local Graal test cases (including [one of the ones](https://github.com/datastax/java-driver/pull/1612#issuecomment-1621981255) referenced on the original PR) and I don't see any fatal regressions.  So far I've only tested with the following VM:

```
$ java -version
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 11.0.18+10-jvmci-22.3-b13)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 11.0.18+10-jvmci-22.3-b13, mixed mode)
```


I am seeing the following set of warnings now which (I believe) are new:

```
> Task :nativeImage                                                                   
========================================================================================================================
GraalVM Native Image: Generating 'keyspaceCount' (executable)...                                 
========================================================================================================================
Warning: Could not register io.netty.handler.codec.compression.Lz4FrameDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.netty.handler.codec.compression.Lz4FrameEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.protobuf.ProtobufDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: com/google/protobuf/ExtensionRegistryLite.
Warning: Could not register io.netty.handler.codec.compression.Lz4FrameDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.netty.handler.codec.compression.Lz4FrameEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.protobuf.ProtobufDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: com/google/protobuf/ExtensionRegistryLite.
[1/7] Initializing...                                                                                    (5.0s @ 0.17GB)
 Version info: 'GraalVM 22.3.1 Java 11 CE'  
 Java version info: '11.0.18+10-jvmci-22.3-b13'
```

I don't _think_ these were introduced by the change in this PR.  Currently working on a quick re-test to confirm.

**Comment by absurdfarce** [comment]
Confirmed: the warnings above appear with the same GraalVM version even when the changes contained in this PR are _not_ present.  Given that result I don't see any reason not to move forward with this.

**Review by absurdfarce — APPROVED** [review]

**Comment by hhughes** [comment]
tests failures appear unrelated, merging

**Comment by onobc** [comment]
Thanks for this PR @hhughes and for all of the effort spent attempting to repro etc @absurdfarce . 

It looks like the issue is labeled for `4.17.0`. Any rough date on when that may be available?

**Comment by absurdfarce** [comment]
@onobc Fortunately version 4.17.0 of the Java driver is already available!  You can get it from Maven Central or from [the release on Github](https://github.com/datastax/java-driver/releases/tag/4.17.0)!

**Pull request merged**
