### PR TITLE
Fail BoundStatement if null values are not set explicitly (JAVA-410).

### PR DESCRIPTION
**Pull request by olim7t**

### CODE REVIEW

**Comment by olim7t** [comment]
Rebased on 2.1.

**Comment by pcmanus** [comment]
Mostly looks good. A few minor remarks:
- In `BoundStatement`, we need to change the implementation of the `isSet` methods. They should not call `wrapper.isNull` anymore (and we need to slightly update the javadoc).
- I'd add a `setToNull` to SettableData (for the sake of native types mainly). Recommending `setBytesUnsafe` feels like a hack.
- I'd throw an `IllegalStateException` exception rather than an `IllegalArgumentException` on the argument that we're given a statement that is in a bad state. But `IllegalArgumentException` is justifiable so leave it as is if you prefer.

**Comment by olim7t** [comment]
Done. I'm fine with `IllegalStateException`.

**Comment by pcmanus** [comment]
Looks good, thanks.

**Pull request merged**
