### PR TITLE
Native protocol v3 support

### PR DESCRIPTION
**Pull request by snazy**

### CODE REVIEW

**Comment by pcmanus** [comment]
This is issue [JAVA-151](https://datastax-oss.atlassian.net/browse/JAVA-151), and I believe my comment on that issue applies to this commit as well.

**Comment by tolbertam** [comment]
Can one of the admins verify this patch?

**Comment by adutra** [comment]
@snazy is this PR already fully merged? Can we close it?

**Comment by snazy** [comment]
it's ok to close this one

**Pull request closed without merging**
