### PR TITLE
[JAVA-1771] Add Driver name and version information

### PR DESCRIPTION
**Pull request by dineshjoshi**
@aholmberg Here's a squashed PR.

### CODE REVIEW

**Review by tolbertam — APPROVED** [review]
Will wait for the C* ticket to be reviewed before merging this, but this looks great!  Thanks for contributing 👍

**Review by olim7t — APPROVED** [review]

**Comment by dineshjoshi** [comment]
hi @olim7t and @tolbertam - [my patch was accepted in the C* trunk.](https://issues.apache.org/jira/browse/CASSANDRA-14275) Could you please merge this in?

**Comment by tolbertam** [comment]
@dineshjoshi, awesome!  Before we merge the PR, could you please [sign the CLA](https://github.com/datastax/java-driver/pull/968#issuecomment-370077178)?

**Comment by iamaleksey** [comment]
@tolbertam @olim7t Dinesh works for Apple - he is already covered by the CLA. @datastax-bot is a liar (:

**Comment by olim7t** [comment]
Closing in favor of #1073; as discussed on the JIRA ticket, we re-implemented this because of CLA issues.

**Pull request closed without merging**
