### PR TITLE
Add sleeps for slower machines to process new keyspaces

### PR DESCRIPTION
**Pull request by joaquincasares**

### CODE REVIEW

**Comment by joaquincasares** [comment]
ok to test

**Comment by joaquincasares** [comment]
retest this please

**Comment by joaquincasares** [comment]
retest this please

**Comment by pcmanus** [comment]
Was that a test of jenkins or should that be merged?

**Comment by joaquincasares** [comment]
retest this please

**Comment by joaquincasares** [comment]
retest this please

**Comment by joaquincasares** [comment]
Sorry for not making a note of it, but yes, I'm testing Jenkin's Pull Request automation + the actual fix that's here. I'll probably open up another pull request for a better fix that I'm currently working on.

**Comment by joaquincasares** [comment]
retest this please

**Comment by joaquincasares** [comment]
restest this please

**Comment by pcmanus** [comment]
Are we good closing this? I think that's the same problem that what's being tracked on https://github.com/datastax/java-driver/pull/99, right?

**Comment by joaquincasares** [comment]
Yup, I'll close this ticket out.

**Pull request closed without merging**
