### PR TITLE
JAVA-1203: Upgrade Metrics to allow usage in OSGi

### PR DESCRIPTION
**Pull request by adutra**

### CODE REVIEW

**Comment by tolbertam** [comment]
There is [an entry in the OSGi FAQ](https://github.com/datastax/java-driver/tree/java1203/faq/osgi#im-getting-the-error-unable-to-access-sunmiscunsafe) about metrics using `sun.misc.Unsafe` that references JAVA-1203.   Should we adjust or remove the FAQ with this change?

**Comment by tolbertam** [comment]
There's a small side effect to this change in that metrics 3.2.2 depends on slf4j-api 1.7.22 (vs. 1.7.7 previously).  We don't list slf4j-api directory in our dependencies (although maybe we should).

Anyways, this is fine, but some tests in `LoggingRetryPolicyIntegrationTest` are failing now as slf4j used to allow us to inline exceptions in log formatting, where this seems to no longer be the case (not sure if intentional or not, digging through slf4j changelogs atm):

slf4j-api 1.7.7:

```
Retrying on request error on next host at consistency LOCAL_ONE (initial consistency: LOCAL_ONE, retries: 0, exception: com.datastax.driver.core.exceptions.ServerError: An unexpected error occurred server side on /127.0.1.1:53494: Server Error)
```

slf4j-api 1.7.22:

```
Retrying on request error on next host at consistency LOCAL_ONE (initial consistency: LOCAL_ONE, retries: 0, exception: {})
com.datastax.driver.core.exceptions.ServerError: An unexpected error occurred server side on /127.0.1.1:53456: Server Error
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:120)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:507)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1075)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:998)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

In any case ultimately this is not a direct issue with this change, just a fun observation.  I'll dig more into this.

**Comment by tolbertam** [comment]
I was able to isolate this to [SLF4J-353](https://jira.qos.ch/browse/SLF4J-353) introduced in slf4j-api 1.7.15. See [JAVA-1469](https://datastax-oss.atlassian.net/browse/JAVA-1469) for more details.  I'll open up a separate PR for that on 3.3.0 and adjust the affected tests.  No further action is needed here, although it'd be nice to merge that PR in first (#845).

**Review by tolbertam — APPROVED** [review]
👍

**Review by olim7t — APPROVED** [review]

**Pull request merged**
