### PR TITLE
JAVA-712 : prevent QueryBuilder.quote() from applying duplicate double quotes

### PR DESCRIPTION
**Pull request by newkek**

### CODE REVIEW

**Comment by olim7t** [comment]
Why does `QueryBuilder.quote` invoke `appendName` in the first place? If the user explicitly asks for quotes, we don't need to look at the string's contents, just apply the quotes blindly. The following should work:

``` java
public static String quote(String columnName) {
    return '"' + columnName + '"';
}
```

`cnamePattern` (which btw stands for column name -- we should rename it for clarity) checks if we need to quote in the following situations:

``` java
update("foo").with(set("v", 1)).where(eq("k", 1))
// "v" is a valid column name, no need to quote:
// UPDATE foo SET v=1 WHERE k=1;

update("foo").with(set("V", 1)).where(eq("k", 1))
// use "V" as provided, but case will still be ignored:
// UPDATE foo SET V=1 WHERE k=1;

update("foo").with(set(quote("V"), 1)).where(eq("k", 1))
// when name is really case-sensitive, the user must quote
// UPDATE foo SET "V"=1 WHERE k=1;

update("foo").with(set("v[0]", 1)).where(eq("k", 1))
// that's why the regex tests for square brackets:
// UPDATE foo SET v[0]=1 WHERE k=1;

select("token(k)").from("foo").where(eq("k", 1))
// special case for token(), although we could have required fcall()
// SELECT token(k) FROM foo WHERE k=1;

select("my column").from("foo").where(eq("k", 1))
// that's the case where the regex doesn't match and we add the quotes:
// SELECT "my column" FROM foo WHERE k=1;
```

**Comment by newkek** [comment]
I agree for `quote()`. I just would like to mention that the object mappers uses `quote()` for field names. Hence I think not making any pattern verification here is not really ideal/safe. We could maybe have a pattern to match quoted identifiers. 

Also, the actual cnamePattern (if you think the name is not clear enough we could change to columnNamePattern indeed) does not match function names and, when you want to use for example, `QueryBuilder.select(String[])` with a function name String, it won't work since `Utils.joinAndAppendNames()` will apply quotes. What do you think if we expand cnamePattern only to match function names ?

**Comment by olim7t** [comment]
> I just would like to mention that the object mappers uses quote() for field names. Hence I think not making any pattern verification here is not really ideal/safe.

`quote()` is not supposed to make any verification on its input, just quote it.

> cnamePattern [...] does not match function names

And it's not supposed to. If you want function calls in a select statement, you're supposed to use `select().fcall(...)`, not `select(String...)` only deals with column names.

**Comment by olim7t** [comment]
... so the mapper can't call `select(String...)` directly and expect it to handle computed values.

**Comment by newkek** [comment]
Ok so currently there is no way to make a select with column names _and_ computed values then with the QueryBuilder.

**Comment by olim7t** [comment]
There is, you need to chain them to your select one by one:

``` java
select().column("v").fcall("f", column("v")).from("foo").where(eq("k", 1));
// => SELECT v,f(v) FROM foo WHERE k=1;
```

**Comment by newkek** [comment]
Ok so I will make the changes.

**Comment by olim7t** [comment]
Force-pushed to rebase on 2.1 and add a simple unit test.
Looks ready to go.

**Pull request merged**
