### PR TITLE
Fix unwanted LBP notifications when a contact host is down (JAVA-613).

### PR DESCRIPTION
**Pull request by olim7t**

### CODE REVIEW

**Comment by tolbertam** [comment]
Other then my comment about the unit test, this looks good to me :+1:

**Comment by olim7t** [comment]
Yes, when the driver is initializing, the contact points are tried in order, and once a connection succeeds, the remaining hosts are passed as ADDED (rationale: we don't want to waste time trying all the contact points, but if we tried some of them and know they are down, it's better to mark them down right now rather than retrying them later in the init process).

The test does rely on the iteration order of `Metadata.hosts`. This depends on the hashcodes of the hosts, which are computed from their IP addresses. I had assumed that this wouldn't change across environments but now I realize that what can change are the IPs, depending on `CCMBridge.IP_PREFIX`.

I agree with your commit and I would have done it the same way, but as you noted JAVA-618 break this again. So I guess the only option left is to retry.

**Comment by olim7t** [comment]
Implemented the retry in the test.

**Comment by tolbertam** [comment]
I like the idea of the retry w/ JAVA-618 being a future possibility, and it looks good to me!   I think 10 attempts should be sufficient, there's a theoretical ~1/1000 (2^-10) chance of the test failing, if that ever gives us problems we could bump up maxTries. :+1:

**Comment by olim7t** [comment]
Merged manually to `2.0.9_fixes` (it doesn't show as merged here because that was not the original target).

**Pull request closed without merging**
