### PR TITLE
Adds Windows support to CCMBridge

### PR DESCRIPTION
**Pull request by blerer**
The test using CCM were not working on Windows. This patch change CCMBridge to fix that problem.

### CODE REVIEW

**Comment by tolbertam** [comment]
Nice work!  I had a few comments, but your PR is very timely as we are expanding our automation infrastructure to support windows.

**Comment by blerer** [comment]
My mistake, I did not realize that a new file with the py extension is now created by the ccm setup (https://github.com/pcmanus/ccm/issues/230). I was still using the ccm file coming from the sources. In this case it is true that Windows can directly resolve the file from the path. I modified my patch.

**Comment by tolbertam** [comment]
Sounds good, your recent commit seems to be working great.  I think if you have '.py' in the PATHEXT environment variable the 'cmd /c ccm.py' isn't necessary and you can just use 'ccm' instead, but I like the way you've done it as it is one less thing to need to configure for windows use.  :+1:.  

@olim7t can we merge this?

**Comment by tolbertam** [comment]
Can one of the admins verify this patch?

**Pull request merged**
