### PR TITLE
generate an OSGi-compliant jar (bundle)

### PR DESCRIPTION
**Pull request by eevans**
An OSGi "bundle" is simply a jar file with some additional metadata in the manifest needed by OSGi containers; Non-OSGi environments will simply ignore these extra, unknown, fields.

### CODE REVIEW

**Comment by pcmanus** [comment]
Actually, I've tried committing this but this seems to break some of the test targets. More precisely, we use "profile" for tests and when you do "mvn clean test -Pshort", it gives me:

```
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.datastax.cassandra:cassandra-driver-core:1.0.4-SNAPSHOT (/home/mcmanus/Git/java-driver/driver-core/pom.xml) has 1 error
[ERROR]     Unknown packaging: bundle @ line 24, column 14
```

No real clue why, this seems some incompatibility somewhere. Everything works fine without the '-Pshort'.

As a side note, we have a ticket open for OSGi bundling (https://datastax-oss.atlassian.net/browse/JAVA-142) so maybe the discussion could move there.

**Comment by im2kul** [comment]
Hi,

  Your evaluation to make it an OSGi jar is missing a few key requirements. You have to make sure that you package all the dependencies in a single jar. If the dependent jars are not OSGi enabled, then this is no longer a trivial work. As pcmanus said, creating an OSGi bundle for DataStax core is very useful. I am currently in the same boat and facing this issue. I keep getting errors like Unable to resolve 1.0: missing requirement [1.0] osgi.wiring.package; (&(osgi.wiring.package=com.codahale.metrics)(version>=3.0.0)(!(version>=4.0.0))) etc.

Thanks
Masti

**Comment by eevans** [comment]
> You have to make sure that you package all the dependencies in a single jar.

No, I don't think this is this case.  Like any other OSGi bundle, you have to install the bundles that export the packages this one imports.

You are right that some of the dependencies are not bundles, but they work for me when I wrap them (I'm using Karaf).  Either way though, embedding the dependencies would not be the answer; Getting the dependencies OSGi-enabled as well is the Right Thing(tm) to do.

And for what it's worth, none of this applies to `metrics-core`, it _is_ an OSGi bundle.  If you install it that error should go away.

**Comment by pcmanus** [comment]
Alright, the last commit does fix the test targets and while I'm nowhere near an OSGi expert, embedding all dependencies definitively don't sound like the right way. So committed (I've cherry-picked, mainly because I wanted to commit to the 1.0 branch first) and if that turns out to be "not enough", we can always improve it later.

**Pull request closed without merging**
