### PR TITLE
Make TableOrView public to allow TableOrView.Option to be referenced outside package.

### PR DESCRIPTION
**Pull request by adutra**
Initially reported by DevCenter team.

### CODE REVIEW

**Comment by olim7t** [comment]
I understand the rationale but making it public means we commit to its public/protected API forever. This raises a couple of issues:
- the name is not great
- could be an issue if we need to refactor in the future (e.g. add intermediary abstract classes in the hierarchy...)

Another way to approach this would be to make `Options` a top-level class (and rename it maybe), would that work?

On a side note, `nullInitializedList` can be replaced by `Collections.fill`.

**Comment by adutra** [comment]
Ok for making Options a top-level class, but do you have any suggestion for its name? I can't think of anything suitable :)

**Comment by adutra** [comment]
Turns out that `Collections.fill` is not suitable, but `Collections.nCopies` works.

**Comment by olim7t** [comment]
Made the class top-level and renamed it to `TableOptionsMetadata`.

I accidentally rebased my local branch (sorry about that), so I ended up squashing my changes to the initial commit.

**Comment by tolbertam** [comment]
I rebased on 3.0 (was some merge conflicts due to changes for #478).  This looks good to me :+1:

**Pull request merged**
