### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by golem131**
- netty 4.0.47 -> 4.0.53
- netty-tcnative 2.0.1 -> 2.0.7
- metrics 3.2.2 - > 3.2.5
- snappy 1.1.2.6 -> 1.1.4
- jackson 2.8.8 -> 2.9.0
- joda 2.9.1 -> 2.9.9
- byteman 3.0.8 -> 3.0.10

### CODE REVIEW

**Review by tolbertam — COMMENTED** [review]
Hi @golem131 , while generally I agree it is good to keep dependencies up to date, we are currently near the end of our test cycle for this release.  We will consider upgrading our dependencies for the next release.

**Comment by golem131** [comment]
@tolbertam what release branch would be next? 4.X or 3.11.X?
Anyway, no problem, i'll rebase this PR later.

**Comment by tolbertam** [comment]
3.x is still a good target branch, so it's ok to leave this is as is for now, thanks! 👍

**Comment by golem131** [comment]
@tolbertam i updated this PR

**Comment by tolbertam** [comment]
I went ahead and created #959 with all the latest updates, thanks!

**Pull request closed without merging**
