### PR TITLE
Added changes to support columns list for GET queries.

### PR DESCRIPTION
**Pull request by vagifzeynalov**
Example:

```
public T get(K1 pk1, K2 pk2, Set<String> columns) {
    return mapper().get(pk1, pk2, columns);
}

final Entity entiry = dao.get(key1, key2, ImmutableSet.of("col1", "col2"));
```

### CODE REVIEW

**Comment by vagifzeynalov** [comment]
Hi guys!
Here is a quick example how it works
https://github.com/vagifzeynalov/dbl_dse_example/tree/mapper_add_columns_for_get
Especially this test file https://github.com/vagifzeynalov/dbl_dse_example/blob/mapper_add_columns_for_get/src/test/java/com/zeynalov/rw/core/dbl/dao/UserAddressDaoTest.java

**Comment by olim7t** [comment]
Is the goal to restrict the columns in the SELECT statement?
One problem I see is that `Set<String>` is a valid type for a partition key component, for example with this table:

``` sql
CREATE TABLE foo(s frozen<set<text>> PRIMARY KEY );
```

**Comment by vagifzeynalov** [comment]
Yes, you've got the goal right.
Actually it could be some special class for columns, like Columns extends HashSet< String >, or even List instead... I don't know what is the best in terms of the compatibility.
Do you want me to change it, or you can change it by yourself?

**Comment by adutra** [comment]
Closing in favor of #645 as this should target a minor release, not a patch one. Thanks!

**Pull request closed without merging**
