### PR TITLE
CASSANDRA-18969 headers [4.1.0_fixes]

### PR DESCRIPTION
**Pull request by Claudenw**
Changes as per RAT tool

### CODE REVIEW

**Comment by Claudenw** [comment]
RAT still reports the following files without headers.  However, I believe they are all OK

Files with unapproved licenses:
  /home/claude/apache/cassandra-java-driver/.gitignore
  /home/claude/apache/cassandra-java-driver/manual/.nav
  /home/claude/apache/cassandra-java-driver/manual/core/statements/.nav
  /home/claude/apache/cassandra-java-driver/manual/mapper/.nav
  /home/claude/apache/cassandra-java-driver/manual/mapper/daos/.nav
  /home/claude/apache/cassandra-java-driver/manual/query_builder/.nav
  /home/claude/apache/cassandra-java-driver/manual/query_builder/schema/.nav
  /home/claude/apache/cassandra-java-driver/test-infra/src/main/resources/client.crt
  /home/claude/apache/cassandra-java-driver/test-infra/src/main/resources/client.key

**Review by hhughes — APPROVED** [review]
Confirming RAT does not find any other files missing license. LGTM

**Comment by hhughes** [comment]
Please close in favor of #1822 (which retains original contributor credit)

**Comment by absurdfarce** [comment]
Closing based on quick conversation with @Claudenw

**Pull request closed without merging**
