### PR TITLE
Added fixes for Jenkins issues

### PR DESCRIPTION
**Pull request by joaquincasares**
Added a few fixes to take care of race conditions on 2.0 and 2.0+1.2 tests, exception for a 2.0+1.2 querybuilder test, and corrected the import ordering via my new IntelliJ orderings.

### CODE REVIEW

**Comment by pcmanus** [comment]
I don't understand the queryBuilder fix. What is the exception thrown when the protocol v1 is used and why is that "expected"?

**Comment by joaquincasares** [comment]
Sorry, I should have been clearer. This is the exception. If it's not expected, then we've run into a regression. I figured you changed the way DateTypes were handled in protocol version 2.

http://cassci.datastax.com/view/y_Drivers/job/y_java-driver_2.0-1.2.x/45/testReport/junit/com.datastax.driver.core.querybuilder/QueryBuilderExecutionTest/dateHandlingTest/

**Comment by pcmanus** [comment]
This is a regression, namely JAVA-313. This should be fixed now.

Note that the java driver 2.0 should be _fully_ compatible with C\* 1.2, so if something that sounds perfectly legit (like here passing a date to the query builder) is broken, do assume it's a regression.

Can you update the pull request to remove the change to QueryBuilderExecutionTest so we commit the rest?

**Comment by joaquincasares** [comment]
Sounds good. I've made the change.

**Comment by djatnieks** [comment]
+1

**Pull request merged**
