### PR TITLE
JDBC module

### PR DESCRIPTION
**Pull request by adejanovski**
New JDBC wrapper for the core Java driver, added as an external module

### CODE REVIEW

**Comment by tolbertam** [comment]
Can one of the admins verify this patch?

**Comment by sparhomenko** [comment]
Are there any plans on merging this? Our team is trying to create a Liquibase extension to manage Cassandra schema changes with Liquibase, and a JDBC driver like that would be extremely useful.

**Comment by al3xandru** [comment]
@sparhomenko can you please drop me an email (alexp @ datastax.com)? thanks

**Comment by ghost** [comment]
Any news when this will be implemented?
imho, JDBC seems somewhat important for a Java database driver ;-)

**Comment by adutra** [comment]
Hello @JohannesKunzeGfK, we actually tend to think exactly the opposite :) – that is, offering the java driver as a JDBC module could do more harm than good to users.

For further explanation, please refer to the following messages on the Java Driver mailing list:
- https://groups.google.com/a/lists.datastax.com/d/msg/java-driver-user/-im4eN_yZbA/uddCigP1BQAJ
- https://groups.google.com/a/lists.datastax.com/d/msg/java-driver-user/-im4eN_yZbA/i-DxxbhnAQAJ

**Comment by al3xandru** [comment]
Currently providing a JDBC wrapper for the driver will create more confusion and surface potentially frustrating limitations of the JDBC spec when forced against Cassandra.

**Comment by gnomed** [comment]
So you're refusing to implement a JDBC driver because it might be limited to a subset of the overall functionality of Cassandra? Even though the datastax website lists a JDBC driver on the roadmap for java development? (http://docs.datastax.com/en/developer/java-driver/3.0/common/drivers/introduction/introArchOverview_c.html) And presumably people using JDBC should realize it is not the native interface and should not expect full functionality.

Honestly, I get the philosophy, but I have tools already written to use jdbc and if my use case is simple, a jdbc driver would save me a lot of time re-inventing the wheel. I'm disappointed this is the decision that was made.

**Comment by al3xandru** [comment]
@gnomed, it would be really helpful if you could ping me (alexp @ datastax) with more details about the tools/integrations you have on your list.

I understand how this might look disappointing, but it wasn't an easy decision and we had looked at various scenarios and use cases, and weighed in many factors.

**Comment by adejanovski** [comment]
@gnomed the (unofficial) JDBC wrapper for the Datastax Java Driver can be found here : https://github.com/adejanovski/cassandra-jdbc-wrapper

**Comment by gnomed** [comment]
@al3xandru email sent, thanks for reaching out. No major expectations at all.

@adejanovski thanks a bunch for the link. I was purposely looking for an "official" solution (since I guess datastax is the official sponsor for cql driver development according to the [apache wiki](http://wiki.apache.org/cassandra/GettingStarted)), but looks like the official word is that I will have to settle for something unofficial so this looks like the next best thing. Thanks

**Comment by ghuser** [comment]
For the record. There is also another jdbc driver wrapper based on this driver: https://bitbucket.org/dbschema/cassandra-jdbc-driver/src/master/

It is maintained and used by [dbschema](https://dbschema.com/) software

**Pull request closed without merging**
