### PR TITLE
JAVA-922: TypeCodec returns unmodifiable collections.

### PR DESCRIPTION
**Pull request by adutra**

### CODE REVIEW

**Comment by olim7t** [comment]
Looks good to me. We can probably squash all commits together.
One small remark: could you describe what the commit does instead of what the problem was, i.e. "TypeCodec returns unmodifiable collections" => "Make TypeCodec return mutable collections".

**Comment by adutra** [comment]
Rebased and squashed. I also followed your suggestion concerning the Row class and changed the commit message as per your suggestion.

**Comment by tolbertam** [comment]
looks good to me as well, :+1:

**Comment by olim7t** [comment]
Closed in favor of #485 (which targets 3.0)

**Pull request closed without merging**
