### PR TITLE
removed jackson dependency, fixed invalid CQL order by syntax

### PR DESCRIPTION
**Pull request by briandilley**
Changed from an old version of jackson to json.org
Fixed order by statements for CQL select.

### CODE REVIEW

**Comment by ash2k** [comment]
It's a bad idea to use org.json.

**Comment by briandilley** [comment]
well, i could change it to use the latest version of Jackson.  Jackson just seemed like overkill to me, but mainly it was using an older version.

**Comment by pcmanus** [comment]
I've fixed the query builder syntax, thanks for that.

As for the jackson 1.4 dependency, it is already pulled by cassandra-all anyway, so there's little point in changing it. We will try to minimize further the driver dependency in the future, but this will have to start by removing the dependency on cassandra-all which itself will require [CASSANDRA-4623](https://issues.apache.org/jira/browse/CASSANDRA-4623) first. As for Jackson, it's not used anywhere performance sensitive so I don't think it's worth bothering which version is used exactly.

As a side note, I'd suggest avoiding unrelated changes in the same pull request.

**Comment by briandilley** [comment]
thanks.

i did a single pull request because github wouldn't let me create more than one :/

**Pull request closed without merging**
