### PR TITLE
JAVA-2460: Document how to determine the local DC

### PR DESCRIPTION
**Pull request by adutra**

### CODE REVIEW

**Review by tomekl007 — APPROVED** [review]

**Comment by jorgebay** [comment]
Looks great, I would take the opportunity to remove references about no alternatives to the default, e.g., "No out-of-the-box alternatives, but you can write your own." from the doc.

**Comment by adutra** [comment]
> Looks great, I would take the opportunity to remove references about no alternatives to the default, e.g., "No out-of-the-box alternatives, but you can write your own." from the doc.

Do you think we should mention the other ones (basic and dc-inferring)? I thought we would keep them "hidden"...

**Comment by jorgebay** [comment]
yes, its ok not to mention them, but saying "No out-of-the-box alternatives" can be misleading.

In that case, removing the bullet point would be better IMO

**Review by jorgebay — APPROVED** [review]
+1

**Pull request merged**
