### PR TITLE
Add test JAVA-467

### PR DESCRIPTION
**Pull request by pingtimeout**

### CODE REVIEW

**Comment by pingtimeout** [comment]
Please do not merge yet as I will probably find new tests to add

**Comment by olim7t** [comment]
I'm merging this to my local repo because I need to make some changes on top of it.

**Comment by pingtimeout** [comment]
I do not have any other test to have so I am ok for this PR to be merged

**Comment by olim7t** [comment]
Merged manually in 3db9df3f25c65a6c2724866c3f791607d92d0cde, I accidentally rebased at some point so it doesn't show here.

**Pull request closed without merging**
