### PR TITLE
Proper schema disagreement fix

### PR DESCRIPTION
**Pull request by joaquincasares**

### CODE REVIEW

**Comment by joaquincasares** [comment]
retest please

**Comment by joaquincasares** [comment]
retest this please

**Comment by pcmanus** [comment]
This should not be necessary, the driver already waits for schema agreement when a schema modifying query is performed. If it doesn't work correctly, we need to understand why and fix it in the driver, no the tests.

**Comment by joaquincasares** [comment]
This is constantly reproducible by the 3rd test in our Jenkins server where the test machine (or VM?) is a bit slower than mine.

@pawel-kaplanski is seeing the same in the C# Driver, fwiw.

**Comment by pcmanus** [comment]
> This is constantly reproducible by the 3rd test in our Jenkins server

What is the error? I'll check the jenkins server when I have a minute but since it's not currently public, mind sharing the error?

**Comment by joaquincasares** [comment]
Jenkins is acting up right now, but I'm pretty sure the error was something like: "ks" does not exist!

https://github.com/datastax/java-driver/blob/master/driver-core/src/test/java/com/datastax/driver/core/AbstractPoliciesTest.java#L52

If I add the sleeps of #95 it passed the entire long test suite, or at least I thought, before Jenkins started acting up.

**Comment by joaquincasares** [comment]
From a recent run of #95:

```
com.datastax.driver.core.exceptions.InvalidQueryException: Keyspace 'ks' does not exist
    at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:35)
    at com.datastax.driver.core.ResultSetFuture.extractCauseFromExecutionException(ResultSetFuture.java:214)
    at com.datastax.driver.core.ResultSetFuture.getUninterruptibly(ResultSetFuture.java:169)
    at com.datastax.driver.core.Session.execute(Session.java:106)
    at com.datastax.driver.core.Session.execute(Session.java:75)
    at com.datastax.driver.core.AbstractPoliciesTest.createMultiDCSchema(AbstractPoliciesTest.java:68)
    at com.datastax.driver.core.ConsistencyTest.testRFThreeDowngradingCLTwoDCs(ConsistencyTest.java:643)
```

**Comment by pcmanus** [comment]
Yeah, it seems I've misplaced the schema agreement check in the driver. I'll fix soonish but in the meantime can you just create a jira ticket?

**Comment by joaquincasares** [comment]
Sure thing. Also, check the last run of the Jenkins server.

Could we add a check to ensure all nodes are up with when c is created (example: `CCMBridge.CCMCluster c = CCMBridge.buildCluster(3, 3, builder);`)?

We're hitting other race conditions when it assumes the nodes are up. I'm assuming that's why the NPE's escape my schemaAgreement checking code.

**Comment by pcmanus** [comment]
Actually, looking at this closer, the schema agreement check should work. I did pushed a few additional log lines to master to help understand what happens.

Can you try to reproduce the failure you see with jenkins with debug logging enabled and attach the resulting log? (If you can reproduce with trace logging that's even better I guess).

**Comment by pcmanus** [comment]
Joaquin, did you had the change to reproduce this problem with a recent build and debug logging enabled?

**Comment by joaquincasares** [comment]
Unfortunately not. Once I wrap up my current tasks, I'll move back to into my automated tasks and post this.

**Comment by joaquincasares** [comment]
I've opened up #114 to fix the issue on the test harness side.

I was able to get TRACE logging from commit 36ea7e0583fcbdb7ae41bfe87cdf2128425d17a3:
http://aep.appspot.com/display/ziKZLhx87MRQicVUV_hDT12U9Zo/

I will be reverting the TRACE commit and continuing to patch the test harness side of things.

**Comment by joaquincasares** [comment]
Cherry-picked 57e7e800c2d9acb2d12c17c318db1e88209e877d since Jenkins hit this issue again. This will ensure when a single test hits a race condition, all subsequent will still be tested individually.

**Pull request closed without merging**
