### PR TITLE
Add new C* 2.1 metadata (JAVA-375).

### PR DESCRIPTION
**Pull request by olim7t**

### CODE REVIEW

**Comment by pcmanus** [comment]
Mostly look good. But if we're changing getIndexInterval() to return an Integer, maybe we can make it return null for C\* < 2.0 too (for consistency sake).

**Comment by olim7t** [comment]
I think it makes sense to still distinguish "it exists but it's not exposed" (default value) from "it does not exist" (null).

**Comment by pcmanus** [comment]
> I think it makes sense to still distinguish "it exists but it's not exposed" (default value) from "it does not exist" (null).

But that's at the price of being able to distinguis between "it exists, is exposed and has default value" from "it exists but is not exposed" so I don't think that's an improvement. More importantly, returning a default value will mainly make people think that it _is_ the value configured in their cluster, while on 1.2 it won't be. To some extend, it's _worth_ to return a default value when the value exists but is not exposed.

**Comment by olim7t** [comment]
Done. I also realized that I had forgotten to update `asCQLQuery`, so I fixed that too.

Note that `rows_per_partition_to_cache` is not in C\* 2.1.0-rc2, so the generated statement fails. But I guess we aim at compatibility with stable versions.

**Comment by pcmanus** [comment]
> Note that rows_per_partition_to_cache is not in C\* 2.1.0-rc2, so the generated statement fails. But I guess we aim at compatibility with stable versions.

Right, that's because `rows_per_partition_to_cache` is actually not what we should use. I'm not sure why it's still in the schema table, I'll check Cassandra side, but it's never set so we should ignore it. What we need to handle is the change to the `caching` value in the system table.
Namely, the `caching` option will now be a "json" map that will contain something like `{"keys": "ALL", "rows_per_partition": 100}`. So basically we need to change the output of getCaching() to be a map.

**Comment by olim7t** [comment]
Squashed to existing commit.

For `asCQLQuery`, it doesn't behave like other options map: strings need to be double-quoted since the json appears in a single-quoted string, and `rows_per_partition` must be a string, not an actual int.

**Comment by pcmanus** [comment]
Regarding the getCaching map, I don't see the point of adding a custom (unknown to C*) "legacy_caching" option. Let's just just use "keys" since that's what it is.

> For asCQLQuery, it doesn't behave like other options map: strings need to be double-quoted since the json appears in a single-quoted string, and rows_per_partition must be a string, not an actual int.

Have you tested it? For CQL, the syntax to use should be an normal CQL map with simple quotes etc. (so it should use `formatOptionMap` without modifications). What `asCQLQuery` is not the reverse of what is found in the `caching` column of the schema table (I know it's confusing but ...).

**Comment by olim7t** [comment]
OK, I guess I had tried all possible strings but not a simple CQL map...

Squashed again.

**Comment by pcmanus** [comment]
Looks good, thanks

**Pull request merged**
