### PR TITLE
JAVA-827:Add QueryBuilder support for UPDATE ... IF EXISTS

### PR DESCRIPTION
**Pull request by boliza**
this PR should also merge to braches 2.1 and 2.2

### CODE REVIEW

**Comment by adutra** [comment]
Hello @boliza thank you for your contribution.
I think we could be more restrictive regarding situations where `ifExists()` is available.
The `Update` class is indeed a bit too lenient, and allows users to create invalid statements such as:

``` java
update("foo").with(set("x", 1)).where(eq("k", 0)).ifExists().onlyIf(eq("y", 2)).ifExists();
```

Obviously we cannot change the entire class for compatibility reasons; but at least for the new `ifExists()` method, let's try to stick closer to the grammar.
[According to which](https://github.com/iamaleksey/cassandra/blob/31e3f612b113a76ca8c04a3a86aa6df3915ad055/src/java/org/apache/cassandra/cql3/Cql.g#L436-L437), an `IF EXISTS` clause can only appear after a `WHERE` clause, and cannot be followed by anything else.
That said, I would rather create an inner class:

``` java
public static class IfExists extends BuiltStatement.ForwardingStatement<Update> {
    IfExists(Update statement) {
        super(statement);
    }
}
```

Then we could add an entry point in the `Where` class:

``` java
public IfExists ifExists() {
    statement.ifExists = true;
    return new IfExists(statement);
}
```

This way the statement above wouldn't compile. Could you please amend your PR and try this out?
Thanks again!

**Comment by boliza** [comment]
@adutra I will try tomorrow

**Comment by boliza** [comment]
@adutra I think the `Conditions` should like the `IfExists` witch you described. In the CQL SPEC, the if condition clause must not with the is exists clause together. so both `Conditions` and `IfExists`  clause can only appear after a WHERE clause.

Am I right?

**Comment by adutra** [comment]
@boliza You are right in theory but we cannot change the class the way you did because it breaks binary compatibility with older versions. That's why the Travis CI build is failing by the way. We should only adopt the strategy I described for newly-introduced features.

**Comment by adutra** [comment]
@boliza I'm sorry but we need to make hard choices sometimes :) and we're going to merge #413 instead of this one. Thank you very much for your time and commitment to the DataStax Java driver.

**Comment by boliza** [comment]
That's ok. But I still have a question that's is we still can build a update statment like this

```
UPDATE foo SET x=4 WHERE k=0 IF x=1  IF EXISTS;
```

which build from this:

``` java
update("foo").with(set("x", 4)).onlyIf(eq("x", 1)).where(eq("k", 0)).ifExists();
```

**Comment by tolbertam** [comment]
Hi @boliza, I just gave this a try on the other PR and it appears to work.  I noticed you had some additional tests in this PR that I think are useful, so I will add and attribute them to you after that PR gets merged, thanks!

**Comment by boliza** [comment]
@tolbertam I know that PR can work.But sometimes can build invalid statment like this 

``` java
query = "UPDATE foo SET x=4 WHERE k=0 IF x=1 IF EXISTS";
update = update("foo").with(set("x", 4)).onlyIf(eq("x", 1)).where(eq("k", 0)).ifExists();
assertEquals(update.toString(), query);
```

this test can pass but the `query` can't execute in cassandra.

**Comment by tolbertam** [comment]
Ah, I see what you are saying.  That is technically an invalid statement, but I don't think QueryBuilder prevents from creating invalid queries in other cases as well.

**Pull request closed without merging**
