### PR TITLE
unbreak of jvm shutdown hooks

### PR DESCRIPTION
**Pull request by damoon**
this change makes sure the drivers does not keep the jvm running on its own.
now the jvm can detect that all work is done and start to shutdown.
while shutting down registered hooks can be used to stop the driver.

cluster building and closing can be placed close the each other (in the source code) as suggested in:
https://code.google.com/p/google-guice/wiki/ModulesShouldBeFastAndSideEffectFree

### CODE REVIEW

**Comment by damoon** [comment]
the added test looks good to me, even so i could not actually run it. ccm complained about my JAVA_HOME. would be nice if someone could run the test... :D

**Comment by pcmanus** [comment]
I think we already talked about this, but I'm still not entirely sold on the fact that using daemon threads is the right thing to do. If you shutdown/close your Cluster instance properly, then having daemon threads doesn't matter (since, bug excepted, shutdown/close should close any threads used by the driver properly).

So the question is what do we want to happen If you don't close() properly at the end of our application (which in itself is a bug, a misuse of the driver)? Currently, the application will keep the JVM running, yes, but that's not a bad way imo to make you realize that you forgot to close things properly. Once you realize it, you can go back to you code and add the close. If we use only daemon threads however, in the same situation, the jvm will exit normally, even though you haven't closed things properly (which means in particular that some of your asynchronous requests may end up not being persisted for instance). Now that's more dangerous because you will thing everything is alright, and may not realized that you forgot to close properly until it bite you.

Now, I'll note that I think I understand your goal: you want to be able put the Cluster.close() in a shutdownHook. But what I'm saying is that I'm not convinced allowing that is worth getting the behavior I described above.

In any case, I'm willing to discuss that further, but since we track issue on JIRA, I'd prefer opening an issue on JIRA (https://datastax-oss.atlassian.net/browse/JAVA) to continue the discussion.

**Comment by zznate** [comment]
It's been a year or two since we dealt with this on Hector, but IIRC, a shutdown hook does not get invoked and will leak the classloader in a managed environment (like Tomcat) when an app is reloaded.

**Comment by tolbertam** [comment]
Can one of the admins verify this patch?

**Comment by adutra** [comment]
Closing as per the discussion above.

**Pull request closed without merging**
