### PR TITLE
JAVA-1011: Expose PoolingOptions defaults values.

### PR DESCRIPTION
**Pull request by newkek**

### CODE REVIEW

**Comment by adutra** [comment]
Missing an entry to the changelog, otherwise :+1:

**Comment by tolbertam** [comment]
looks good to me as well :+1:, we should make note to do a follow on action when merged in 3.0 to add an entry into DEFAULTS for Protocol V4 that references the same map as V3.

**Comment by newkek** [comment]
Pushed the changelog change. Good point @tolbertam, not sure how to do that, maybe opening another PR for 3.0 would be simpler no?

**Comment by tolbertam** [comment]
:+1:  I think that is the correct route to go, another PR after this is merged into 3.0.

**Comment by olim7t** [comment]
:+1: 
It would be nice to have javadocs, at least for the map.
Regarding protocol v4, I think it's better not to duplicate the entries if the values don't change. We can document that you need to use the highest version that's lower than or equal to your version. The immutable map iterates in insertion order, so that's easy to do, even from client code.

**Comment by newkek** [comment]
Pushed the javadoc, thanks for the feedback.

**Comment by olim7t** [comment]
Re-reading my last comment, I realized it would be more logical to use V1 as the first key, to enforce the "highest key <= actual version" rule. I added that in a separate commit.

**Pull request merged**
