### PR TITLE
JAVA-473 : Strategies for saving null fields in mapped objects

### PR DESCRIPTION
**Pull request by newkek**
/!\ This branch has been created from PR #347 so it needs to be merged after #347 .

### CODE REVIEW

**Comment by adutra** [comment]
Nice job, lgtm apart from some minor naming issues.
Also, a mention should be added to the changelog.

**Comment by tolbertam** [comment]
Looks good to me :+1:, will probably need to rebase a littke bit after #347 is merged as you mention.

**Comment by tolbertam** [comment]
Doesn't the change to remove writeConsistency and readConsistency from Table annotation break API compatibility in a way?

**Comment by newkek** [comment]
Yes that was a suggestion but we decided that it will be reverted.

**Comment by olim7t** [comment]
Force-pushed to rebase on latest java477 + a few changes.

**Comment by tolbertam** [comment]
looks good to me! :+1:

**Pull request merged**
